/* ══════════════════════════════════════
   EUROCOPA HISTÓRICA · Datos
   Selecciones y planteles 1960-2024
══════════════════════════════════════ */

const SELECCIONES_EURO = [

/* ── ESPAÑA ── */
{ id:'spain', nombre:'España', flag:'🇪🇸', ediciones:[
  { año:1964, jugadores:[
    {n:'Iribar',       pos:'pt', v:85},{n:'Betancort',     pos:'pt', v:74},
    {n:'Calleja',      pos:'def',sp:'lb',v:76},{n:'Olivella',     pos:'def',sp:'cb',v:77},
    {n:'Zoco',         pos:'def',sp:'cb',v:78},{n:'Reija',         pos:'def',sp:'lb',v:74},
    {n:'Fusté',        pos:'med',v:79},{n:'Suárez L.',     pos:'med',v:87},{n:'Adelardo',pos:'med',v:79},
    {n:'Amancio',      pos:'del',sp:'ext',v:83},{n:'Gento',        pos:'del',sp:'ext',v:88},
    {n:'Marcelino',    pos:'del',sp:'dc', v:80},{n:'Pereda',       pos:'del',sp:'ext',v:78},
  ]},
  { año:1984, jugadores:[
    {n:'Arconada',     pos:'pt', v:88},{n:'Zubizarreta',   pos:'pt', v:84},
    {n:'Camacho',      pos:'def',sp:'cb',v:84},{n:'Julio Alberto', pos:'def',sp:'lb',v:78},
    {n:'Sanchís',      pos:'def',sp:'cb',v:80},{n:'Maceda',        pos:'def',sp:'cb',v:77},
    {n:'Gallego',      pos:'med',v:76},{n:'Víctor',        pos:'med',v:79},{n:'González',pos:'med',v:75},
    {n:'Carrasco',     pos:'del',sp:'ext',v:79},{n:'Santillana',    pos:'del',sp:'dc', v:83},
    {n:'Salinas',      pos:'del',sp:'dc', v:81},{n:'Señor',         pos:'del',sp:'ext',v:77},
  ]},
  { año:2008, jugadores:[
    {n:'Casillas',     pos:'pt', v:93},{n:'Reina',         pos:'pt', v:85},
    {n:'Ramos',        pos:'def',sp:'cb',v:87},{n:'Marchena',      pos:'def',sp:'cb',v:81},
    {n:'Capdevila',    pos:'def',sp:'lb',v:80},{n:'Puyol',         pos:'def',sp:'cb',v:88},
    {n:'Senna',        pos:'med',v:82},{n:'Xavi',          pos:'med',v:94},{n:'Iniesta',pos:'med',v:93},{n:'Fàbregas',pos:'med',v:86},
    {n:'Villa',        pos:'del',sp:'dc', v:90},{n:'Torres',       pos:'del',sp:'dc', v:89},
    {n:'Silva D.',     pos:'del',sp:'ext',v:87},{n:'Güiza',        pos:'del',sp:'dc', v:81},
  ]},
  { año:2012, jugadores:[
    {n:'Casillas',     pos:'pt', v:92},{n:'Valdés',        pos:'pt', v:86},
    {n:'Ramos',        pos:'def',sp:'cb',v:89},{n:'Piqué',         pos:'def',sp:'cb',v:88},
    {n:'Alba',         pos:'def',sp:'lb',v:85},{n:'Arbeloa',       pos:'def',sp:'lb',v:77},
    {n:'Busquets',     pos:'med',v:89},{n:'Xavi',          pos:'med',v:92},{n:'Iniesta',pos:'med',v:94},
    {n:'Silva D.',     pos:'del',sp:'ext',v:89},{n:'Torres',       pos:'del',sp:'dc', v:85},
    {n:'Villa',        pos:'del',sp:'dc', v:87},{n:'Pedro',        pos:'del',sp:'ext',v:83},
  ]},
  { año:2016, jugadores:[
    {n:'CASILLAS',     pos:'pt', v:82},{n:'DE GEA',         pos:'pt', v:88},
    {n:'RAMOS',        pos:'def',sp:'cb',v:91},{n:'PIQUÉ',         pos:'def',sp:'cb',v:88},
    {n:'ALBA',         pos:'def',sp:'lb',v:86},{n:'AZPILICUETA',   pos:'def',sp:'lb',v:82},
    {n:'BUSQUETS',     pos:'med',v:89},{n:'INIESTA',        pos:'med',v:91},{n:'SILVA D.',pos:'med',v:90},
    {n:'KOKE',         pos:'med',v:83},{n:'FABREGAS',       pos:'med',v:85},
    {n:'PEDRO',        pos:'del',sp:'ext',v:83},{n:'MORATA',        pos:'del',sp:'dc', v:83},
    {n:'NOLITO',       pos:'del',sp:'ext',v:81},{n:'ALCACER',       pos:'del',sp:'dc', v:79},
  ]},
  { año:2021, jugadores:[
    {n:'SIMÓN U.',     pos:'pt', v:84},{n:'DE GEA',         pos:'pt', v:87},
    {n:'LAPORTE',      pos:'def',sp:'cb',v:87},{n:'PAU TORRES',    pos:'def',sp:'cb',v:84},
    {n:'ALBA',         pos:'def',sp:'lb',v:84},{n:'AZPILICUETA',   pos:'def',sp:'lb',v:82},
    {n:'BUSQUETS',     pos:'med',v:86},{n:'KOKE',           pos:'med',v:84},{n:'PEDRI',   pos:'med',v:87},
    {n:'DANI OLMO',    pos:'med',v:85},{n:'THIAGO',         pos:'med',v:84},
    {n:'MORATA',       pos:'del',sp:'dc', v:84},{n:'MORENO G.',    pos:'del',sp:'dc', v:85},
    {n:'OYARZABAL',    pos:'del',sp:'ext',v:83},{n:'F. TORRES',    pos:'del',sp:'ext',v:83},
  ]},
  { año:2024, jugadores:[
    {n:'SIMÓN',        pos:'pt', v:88},{n:'RAYA',           pos:'pt', v:83},
    {n:'CARVAJAL',     pos:'def',sp:'lb',v:83},{n:'LE NORMAND',    pos:'def',sp:'cb',v:82},
    {n:'LAPORTE',      pos:'def',sp:'cb',v:84},{n:'CUCURELLA',     pos:'def',sp:'lb',v:79},
    {n:'RODRI',        pos:'med',v:94},{n:'FABIÁN RUIZ',   pos:'med',v:86},{n:'PEDRI',   pos:'med',v:90},
    {n:'WILLIAMS N.',  pos:'del',sp:'ext',v:87},{n:'MORATA',       pos:'del',sp:'dc', v:84},
    {n:'LAMINE YAMAL', pos:'del',sp:'ext',v:91},{n:'OLMO',         pos:'del',sp:'ext',v:87},
  ]},
]},

/* ── ALEMANIA / ALEMANIA OCCIDENTAL ── */
{ id:'germany', nombre:'Alemania', flag:'🇩🇪', ediciones:[
  { año:1972, jugadores:[
    {n:'Maier',        pos:'pt', v:92},{n:'Wolter',        pos:'pt', v:74},
    {n:'Höttges',      pos:'def',sp:'lb',v:76},{n:'Schwarzenbeck', pos:'def',sp:'cb',v:82},
    {n:'Beckenbauer',  pos:'def',sp:'cb',v:97},{n:'Breitner',      pos:'def',sp:'lb',v:85},
    {n:'Wimmer',       pos:'med',v:78},{n:'Netzer',        pos:'med',v:90},{n:'Hoeness',pos:'med',v:82},
    {n:'Heynckes',     pos:'del',sp:'dc', v:83},{n:'Müller G.',    pos:'del',sp:'dc', v:97},
    {n:'Kremers',      pos:'del',sp:'ext',v:79},{n:'Grabowski',    pos:'del',sp:'ext',v:81},
  ]},
  { año:1980, jugadores:[
    {n:'Schumacher',   pos:'pt', v:87},{n:'Kargus',        pos:'pt', v:74},
    {n:'Kaltz',        pos:'def',sp:'lb',v:81},{n:'Stielike',      pos:'def',sp:'cb',v:83},
    {n:'Dietz',        pos:'def',sp:'cb',v:78},{n:'Briegel',       pos:'def',sp:'lb',v:79},
    {n:'H. Müller',    pos:'med',v:80},{n:'Schuster',      pos:'med',v:85},{n:'Hrubesch',pos:'del',sp:'dc',v:83},
    {n:'Allofs K.',    pos:'del',sp:'ext',v:83},{n:'Rummenigge',   pos:'del',sp:'ext',v:90},
    {n:'Fischer K-H.', pos:'del',sp:'dc', v:82},{n:'Bernd Cullmann',pos:'med',v:77},
  ]},
  { año:1996, jugadores:[
    {n:'Köpke',        pos:'pt', v:83},{n:'Kahn',          pos:'pt', v:88},
    {n:'Helmer',       pos:'def',sp:'cb',v:82},{n:'Sammer',        pos:'def',sp:'cb',v:89},
    {n:'Ziege',        pos:'def',sp:'lb',v:82},{n:'Reuter',        pos:'def',sp:'lb',v:79},
    {n:'Eilts',        pos:'med',v:78},{n:'Strunz',        pos:'med',v:76},{n:'Scholl',  pos:'med',v:82},
    {n:'Babbel',       pos:'def',sp:'lb',v:79},
    {n:'Bierhoff',     pos:'del',sp:'dc', v:84},{n:'Klinsmann',    pos:'del',sp:'dc', v:88},
    {n:'Kuntz',        pos:'del',sp:'dc', v:81},{n:'Bode',         pos:'del',sp:'ext',v:77},
  ]},
  { año:2008, jugadores:[
    {n:'LEHMANN',      pos:'pt', v:84},{n:'ADLER',          pos:'pt', v:78},
    {n:'FRIEDRICH',    pos:'def',sp:'cb',v:82},{n:'MERTESACKER',   pos:'def',sp:'cb',v:83},
    {n:'LAHM',         pos:'def',sp:'lb',v:90},{n:'JANSEN',        pos:'def',sp:'lb',v:78},
    {n:'FRINGS',       pos:'med',v:81},{n:'SCHWEINSTEIGER', pos:'med',v:88},{n:'BALLACK', pos:'med',v:88},
    {n:'PODOLSKI',     pos:'del',sp:'ext',v:85},{n:'KLOSE',        pos:'del',sp:'dc', v:88},
    {n:'GOMEZ',        pos:'del',sp:'dc', v:82},{n:'MÜLLER T.',    pos:'del',sp:'ext',v:86},
  ]},
  { año:2012, jugadores:[
    {n:'NEUER',        pos:'pt', v:93},{n:'ADLER',          pos:'pt', v:79},
    {n:'LAHM',         pos:'def',sp:'lb',v:89},{n:'HUMMELS',       pos:'def',sp:'cb',v:87},
    {n:'BOATENG',      pos:'def',sp:'cb',v:86},{n:'BADSTUBER',     pos:'def',sp:'cb',v:81},
    {n:'SCHWEINSTEIGER',pos:'med',v:89},{n:'KHEDIRA',       pos:'med',v:86},{n:'ÖZIL',    pos:'med',v:89},
    {n:'KROOS',        pos:'med',v:87},{n:'MÜLLER T.',      pos:'del',sp:'ext',v:88},
    {n:'KLOSE',        pos:'del',sp:'dc', v:86},{n:'GOMEZ',        pos:'del',sp:'dc', v:87},
    {n:'PODOLSKI',     pos:'del',sp:'ext',v:83},{n:'REUS',         pos:'del',sp:'ext',v:87},
  ]},
  { año:2016, jugadores:[
    {n:'NEUER',        pos:'pt', v:94},{n:'TER STEGEN',     pos:'pt', v:88},
    {n:'LAHM',         pos:'def',sp:'lb',v:87},{n:'HUMMELS',       pos:'def',sp:'cb',v:90},
    {n:'BOATENG',      pos:'def',sp:'cb',v:87},{n:'KIMMICH',       pos:'def',sp:'lb',v:85},
    {n:'KROOS',        pos:'med',v:91},{n:'KHEDIRA',        pos:'med',v:85},{n:'ÖZIL',    pos:'med',v:89},
    {n:'MÜLLER T.',    pos:'del',sp:'ext',v:88},{n:'REUS',         pos:'del',sp:'ext',v:86},
    {n:'GOMEZ',        pos:'del',sp:'dc', v:83},{n:'DRAXLER',      pos:'del',sp:'ext',v:84},
    {n:'GÖTZE',        pos:'med',v:85},{n:'SCHWEINSTEIGER', pos:'med',v:84},
  ]},
  { año:2021, jugadores:[
    {n:'NEUER',        pos:'pt', v:91},{n:'FLEKKEN',        pos:'pt', v:79},
    {n:'RÜDIGER',      pos:'def',sp:'cb',v:86},{n:'HUMMELS',       pos:'def',sp:'cb',v:85},
    {n:'GOSENS',       pos:'def',sp:'lb',v:83},{n:'KIMMICH',       pos:'med',v:89},
    {n:'GÜNDOĞAN',     pos:'med',v:88},{n:'KROOS',          pos:'med',v:90},{n:'MÜLLER T.',pos:'del',sp:'ext',v:86},
    {n:'HAVERTZ',      pos:'del',sp:'dc', v:87},{n:'GNABRY',       pos:'del',sp:'ext',v:87},
    {n:'SANÉ',         pos:'del',sp:'ext',v:88},{n:'WERNER',       pos:'del',sp:'dc', v:84},
    {n:'GORETZKA',     pos:'med',v:86},{n:'GINTER',         pos:'def',sp:'cb',v:82},
  ]},
  { año:2024, jugadores:[
    {n:'NEUER',        pos:'pt', v:88},{n:'TER STEGEN',     pos:'pt', v:87},
    {n:'RÜDIGER',      pos:'def',sp:'cb',v:87},{n:'SCHLOTTERBECK', pos:'def',sp:'cb',v:84},
    {n:'TAH',          pos:'def',sp:'cb',v:82},{n:'KIMMICH',       pos:'med',v:89},
    {n:'KROOS',        pos:'med',v:90},{n:'GÜNDOĞAN',       pos:'med',v:87},{n:'MUSIALA',pos:'med',v:89},
    {n:'WIRTZ',        pos:'med',v:90},{n:'HAVERTZ',        pos:'del',sp:'dc', v:87},
    {n:'SANÉ',         pos:'del',sp:'ext',v:86},{n:'GNABRY',       pos:'del',sp:'ext',v:85},
    {n:'FULLKRUG',     pos:'del',sp:'dc', v:84},{n:'MITTELSTÄDT',  pos:'def',sp:'lb',v:81},
  ]},
]},

/* ── FRANCIA ── */
{ id:'france', nombre:'Francia', flag:'🇫🇷', ediciones:[
  { año:1984, jugadores:[
    {n:'Bats',         pos:'pt', v:83},{n:'Rust',          pos:'pt', v:74},
    {n:'Bossis',       pos:'def',sp:'cb',v:81},{n:'Boli',         pos:'def',sp:'cb',v:79},
    {n:'Amoros',       pos:'def',sp:'lb',v:80},{n:'Domergue',     pos:'def',sp:'lb',v:77},
    {n:'Tigana',       pos:'med',v:87},{n:'Giresse',       pos:'med',v:85},{n:'Fernandez',pos:'med',v:82},
    {n:'Platini',      pos:'del',sp:'ext',v:97},{n:'Six',          pos:'del',sp:'ext',v:80},
    {n:'Bellone',      pos:'del',sp:'dc', v:79},{n:'Lacombe',      pos:'del',sp:'dc', v:78},
  ]},
  { año:2000, jugadores:[
    {n:'Barthez',      pos:'pt', v:90},{n:'Candela',       pos:'pt', v:74},
    {n:'Thuram',       pos:'def',sp:'lb',v:88},{n:'Blanc',         pos:'def',sp:'cb',v:87},
    {n:'Desailly',     pos:'def',sp:'cb',v:89},{n:'Lizarazu',      pos:'def',sp:'lb',v:84},
    {n:'Vieira',       pos:'med',v:92},{n:'Deschamps',     pos:'med',v:85},{n:'Zidane',  pos:'med',v:97},
    {n:'Djorkaeff',    pos:'del',sp:'ext',v:86},{n:'Henry',        pos:'del',sp:'ext',v:92},
    {n:'Trezeguet',    pos:'del',sp:'dc', v:88},{n:'Pires',        pos:'del',sp:'ext',v:87},
  ]},
  { año:2008, jugadores:[
    {n:'LLORIS',       pos:'pt', v:83},{n:'COUPET',         pos:'pt', v:79},
    {n:'THURAM',       pos:'def',sp:'cb',v:85},{n:'GALLAS',        pos:'def',sp:'cb',v:84},
    {n:'EVRA',         pos:'def',sp:'lb',v:83},{n:'ABIDAL',        pos:'def',sp:'lb',v:84},
    {n:'VIEIRA',       pos:'med',v:84},{n:'MAKÉLÉLÉ',       pos:'med',v:83},{n:'RIBÉRY',  pos:'del',sp:'ext',v:88},
    {n:'BENZEMA',      pos:'del',sp:'dc', v:86},{n:'HENRY',        pos:'del',sp:'ext',v:89},
    {n:'ANELKA',       pos:'del',sp:'dc', v:83},{n:'NASRI',        pos:'med',v:84},
    {n:'DIARRA',       pos:'med',v:80},{n:'SAGNOL',         pos:'def',sp:'lb',v:82},
  ]},
  { año:2012, jugadores:[
    {n:'LLORIS',       pos:'pt', v:87},{n:'MANDANDA',       pos:'pt', v:82},
    {n:'EVRA',         pos:'def',sp:'lb',v:84},{n:'CLICHY',        pos:'def',sp:'lb',v:82},
    {n:'MEXES',        pos:'def',sp:'cb',v:82},{n:'RAMI',          pos:'def',sp:'cb',v:80},
    {n:'MATUIDI',      pos:'med',v:84},{n:'CABAYE',         pos:'med',v:83},{n:'RIBÉRY',  pos:'del',sp:'ext',v:89},
    {n:'BENZEMA',      pos:'del',sp:'dc', v:88},{n:'NASRI',        pos:'med',v:85},
    {n:'GIROUD',       pos:'del',sp:'dc', v:84},{n:'MÉNEZ',        pos:'del',sp:'ext',v:80},
    {n:'DIABY',        pos:'med',v:79},{n:"M'VILA",         pos:'med',v:79},
  ]},
  { año:2016, jugadores:[
    {n:'LLORIS',       pos:'pt', v:88},{n:'MANDANDA',       pos:'pt', v:81},
    {n:'KOSCIELNY',    pos:'def',sp:'cb',v:83},{n:'VARANE',        pos:'def',sp:'cb',v:88},
    {n:'EVRA',         pos:'def',sp:'lb',v:80},{n:'SAGNA',         pos:'def',sp:'lb',v:78},
    {n:'KANTÉ',        pos:'med',v:88},{n:'POGBA',          pos:'med',v:87},{n:'MATUIDI', pos:'med',v:83},
    {n:'PAYET',        pos:'del',sp:'ext',v:87},{n:'GRIEZMANN',    pos:'del',sp:'ext',v:90},
    {n:'GIROUD',       pos:'del',sp:'dc', v:82},{n:'MARTIAL',      pos:'del',sp:'ext',v:80},
  ]},
  { año:2021, jugadores:[
    {n:'LLORIS',       pos:'pt', v:87},{n:'MANDANDA',       pos:'pt', v:79},
    {n:'PAVARD',       pos:'def',sp:'lb',v:82},{n:'VARANE',        pos:'def',sp:'cb',v:89},
    {n:'KIMPEMBE',     pos:'def',sp:'cb',v:82},{n:'L. HERNÁNDEZ',  pos:'def',sp:'lb',v:80},
    {n:'KANTÉ',        pos:'med',v:91},{n:'RABIOT',         pos:'med',v:80},{n:'POGBA',   pos:'med',v:85},
    {n:'MBAPPÉ',       pos:'del',sp:'ext',v:93},{n:'BENZEMA',      pos:'del',sp:'dc', v:92},
    {n:'GRIEZMANN',    pos:'del',sp:'ext',v:88},{n:'DEMBÉLÉ',      pos:'del',sp:'ext',v:84},
  ]},
]},

/* ── ITALIA ── */
{ id:'italy', nombre:'Italia', flag:'🇮🇹', ediciones:[
  { año:1968, jugadores:[
    {n:'Zoff',         pos:'pt', v:90},{n:'Albertosi',     pos:'pt', v:83},
    {n:'Facchetti',    pos:'def',sp:'lb',v:86},{n:'Burgnich',      pos:'def',sp:'cb',v:83},
    {n:'Guarneri',     pos:'def',sp:'cb',v:79},{n:'Rosato',        pos:'def',sp:'lb',v:77},
    {n:'Lodetti',      pos:'med',v:77},{n:'Mazzola',       pos:'med',v:88},{n:'Rivera',  pos:'med',v:90},
    {n:'Domenghini',   pos:'del',sp:'ext',v:82},{n:'Anastasi',     pos:'del',sp:'dc', v:83},
    {n:'Riva',         pos:'del',sp:'dc', v:91},{n:'Prati',        pos:'del',sp:'dc', v:80},
  ]},
  { año:1988, jugadores:[
    {n:'Zenga',        pos:'pt', v:88},{n:'Tacconi',       pos:'pt', v:82},
    {n:'Maldini',      pos:'def',sp:'lb',v:91},{n:'Baresi',        pos:'def',sp:'cb',v:93},
    {n:'Bergomi',      pos:'def',sp:'cb',v:88},{n:'De Agostini',   pos:'def',sp:'lb',v:78},
    {n:'Donadoni',     pos:'med',v:83},{n:'Ancelotti',     pos:'med',v:86},{n:'Giannini',pos:'med',v:85},
    {n:'Mancini',      pos:'del',sp:'ext',v:84},{n:'Vialli',       pos:'del',sp:'dc', v:88},
    {n:'Serena',       pos:'del',sp:'dc', v:79},{n:'De Napoli',    pos:'med',v:78},
  ]},
  { año:2008, jugadores:[
    {n:'BUFFON',       pos:'pt', v:91},{n:'PERUZZI',        pos:'pt', v:76},
    {n:'ZAMBROTTA',    pos:'def',sp:'lb',v:84},{n:'CANNAVARO',     pos:'def',sp:'cb',v:88},
    {n:'MATERAZZI',    pos:'def',sp:'cb',v:82},{n:'GROSSO',        pos:'def',sp:'lb',v:82},
    {n:'PIRLO',        pos:'med',v:90},{n:'GATTUSO',        pos:'med',v:84},{n:'DE ROSSI',pos:'med',v:86},
    {n:'CAMORANESI',   pos:'med',v:81},{n:'TONI',           pos:'del',sp:'dc', v:85},
    {n:'TOTTI',        pos:'del',sp:'dc', v:85},{n:'QUAGLIARELLA', pos:'del',sp:'dc', v:80},
    {n:'PERROTTA',     pos:'med',v:80},{n:'INZAGHI F.',     pos:'del',sp:'dc', v:81},
  ]},
  { año:2012, jugadores:[
    {n:'BUFFON',       pos:'pt', v:89},{n:'MARCHETTI',      pos:'pt', v:80},
    {n:'ABATE',        pos:'def',sp:'lb',v:82},{n:'CHIELLINI',     pos:'def',sp:'cb',v:88},
    {n:'BONUCCI',      pos:'def',sp:'cb',v:87},{n:'BARZAGLI',      pos:'def',sp:'cb',v:85},
    {n:'PIRLO',        pos:'med',v:90},{n:'DE ROSSI',       pos:'med',v:86},{n:'MONTOLIVO',pos:'med',v:82},
    {n:'BALOTELLI',    pos:'del',sp:'dc', v:86},{n:'CASSANO',      pos:'del',sp:'ext',v:84},
    {n:'GIOVINCO',     pos:'del',sp:'ext',v:82},{n:'DIAMANTI',     pos:'med',v:80},
    {n:'NOCERINO',     pos:'med',v:80},{n:'AQUILANI',       pos:'med',v:81},
  ]},
  { año:2016, jugadores:[
    {n:'BUFFON',       pos:'pt', v:88},{n:'SIRIGU',         pos:'pt', v:82},
    {n:'DE SCIGLIO',   pos:'def',sp:'lb',v:80},{n:'CHIELLINI',     pos:'def',sp:'cb',v:88},
    {n:'BONUCCI',      pos:'def',sp:'cb',v:89},{n:'BARZAGLI',      pos:'def',sp:'cb',v:84},
    {n:'PIRLO',        pos:'med',v:88},{n:'DE ROSSI',       pos:'med',v:84},{n:'PAROLO',  pos:'med',v:80},
    {n:'INSIGNE',      pos:'del',sp:'ext',v:85},{n:'PELLÉ',        pos:'del',sp:'dc', v:82},
    {n:'EDER',         pos:'del',sp:'ext',v:80},{n:'EL SHAARAWY',  pos:'del',sp:'ext',v:82},
    {n:'FLORENZI',     pos:'def',sp:'lb',v:82},{n:'CANDREVA',      pos:'del',sp:'ext',v:80},
  ]},
  { año:2021, jugadores:[
    {n:'DONNARUMMA',   pos:'pt', v:92},{n:'SIRIGU',         pos:'pt', v:79},
    {n:'DI LORENZO',   pos:'def',sp:'lb',v:80},{n:'CHIELLINI',     pos:'def',sp:'cb',v:88},
    {n:'BONUCCI',      pos:'def',sp:'cb',v:88},{n:'EMERSON',       pos:'def',sp:'lb',v:78},
    {n:'JORGINHO',     pos:'med',v:86},{n:'VERRATTI',       pos:'med',v:88},{n:'BARELLA', pos:'med',v:87},
    {n:'CHIESA',       pos:'del',sp:'ext',v:86},{n:'INSIGNE',      pos:'del',sp:'ext',v:86},
    {n:'IMMOBILE',     pos:'del',sp:'dc', v:86},{n:'BERARDI',      pos:'del',sp:'ext',v:81},
  ]},
  { año:2024, jugadores:[
    {n:'DONNARUMMA',   pos:'pt', v:90},{n:'MERET',          pos:'pt', v:82},
    {n:'DI LORENZO',   pos:'def',sp:'lb',v:84},{n:'BASTONI',       pos:'def',sp:'cb',v:87},
    {n:'CALAFIORI',    pos:'def',sp:'cb',v:83},{n:'DIMARCO',       pos:'def',sp:'lb',v:84},
    {n:'BARELLA',      pos:'med',v:88},{n:'JORGINHO',       pos:'med',v:84},{n:'FRATTESI', pos:'med',v:83},
    {n:'CHIESA',       pos:'del',sp:'ext',v:86},{n:'SCAMACCA',     pos:'del',sp:'dc', v:83},
    {n:'PELLEGRINI',   pos:'med',v:84},{n:'RETEGUI',        pos:'del',sp:'dc', v:81},
    {n:'ZACCAGNI',     pos:'del',sp:'ext',v:82},{n:'FAGIOLI',      pos:'med',v:80},
  ]},
]},

/* ── PAÍSES BAJOS ── */
{ id:'netherlands', nombre:'Países Bajos', flag:'🇳🇱', ediciones:[
  { año:1976, jugadores:[
    {n:'Schrijvers',   pos:'pt', v:82},{n:'Jongbloed',     pos:'pt', v:79},
    {n:'Suurbier',     pos:'def',sp:'lb',v:80},{n:'Rijsbergen',    pos:'def',sp:'cb',v:79},
    {n:'Krol',         pos:'def',sp:'cb',v:86},{n:'Poortvliet',    pos:'def',sp:'lb',v:76},
    {n:'Neeskens',     pos:'med',v:89},{n:'W. Van Hanegem', pos:'med',v:87},{n:'Haan',   pos:'med',v:80},
    {n:'Rensenbrink',  pos:'del',sp:'ext',v:87},{n:'Rep',           pos:'del',sp:'dc', v:82},
    {n:'Cruyff',       pos:'del',sp:'ext',v:99},{n:'Van der Kerkhof',pos:'del',sp:'ext',v:81},
  ]},
  { año:1988, jugadores:[
    {n:'Van Breukelen',pos:'pt', v:87},{n:'Menzo',         pos:'pt', v:76},
    {n:'Van Aerle',    pos:'def',sp:'lb',v:78},{n:'Koeman R.',     pos:'def',sp:'cb',v:89},
    {n:'Koeman E.',    pos:'def',sp:'cb',v:78},{n:'Van Tiggelen',  pos:'def',sp:'lb',v:79},
    {n:'Rijkaard',     pos:'med',v:91},{n:'Wouters',       pos:'med',v:80},{n:'Muhren',  pos:'med',v:84},
    {n:'Van Basten',   pos:'del',sp:'dc', v:97},{n:'Gullit',       pos:'del',sp:'ext',v:95},
    {n:'Vanenburg',    pos:'del',sp:'ext',v:79},{n:'Winter',       pos:'med',v:77},
  ]},
  { año:2000, jugadores:[
    {n:'Van der Sar',  pos:'pt', v:88},{n:'Westerveld',    pos:'pt', v:78},
    {n:'Stam',         pos:'def',sp:'cb',v:90},{n:'Frank de Boer', pos:'def',sp:'cb',v:86},
    {n:'Van Bronckhorst',pos:'def',sp:'lb',v:82},{n:'Reiziger',    pos:'def',sp:'lb',v:80},
    {n:'Davids',       pos:'med',v:88},{n:'Seedorf',       pos:'med',v:87},{n:'Cocu',    pos:'med',v:82},
    {n:'Bergkamp',     pos:'del',sp:'dc', v:93},{n:'Kluivert',     pos:'del',sp:'dc', v:87},
    {n:'Overmars',     pos:'del',sp:'ext',v:88},{n:'Zenden',       pos:'del',sp:'ext',v:80},
  ]},
  { año:2008, jugadores:[
    {n:'VAN DER SAR',  pos:'pt', v:87},{n:'STEKELENBURG',   pos:'pt', v:81},
    {n:'VAN BRONCKHORST',pos:'def',sp:'lb',v:84},{n:'OOIJER',     pos:'def',sp:'cb',v:79},
    {n:'MATHIJSEN',    pos:'def',sp:'cb',v:80},{n:'BOULAHROUZ',    pos:'def',sp:'cb',v:79},
    {n:'SNEIJDER',     pos:'med',v:90},{n:'VAN DER VAART',  pos:'med',v:86},{n:'DE JONG',  pos:'med',v:83},
    {n:'ROBBEN',       pos:'del',sp:'ext',v:90},{n:'VAN PERSIE',  pos:'del',sp:'dc', v:87},
    {n:'VAN NISTELROOY',pos:'del',sp:'dc', v:86},{n:'KUYT',       pos:'del',sp:'ext',v:83},
    {n:'AFELLAY',      pos:'del',sp:'ext',v:80},{n:'ENGELAAR',    pos:'med',v:78},
  ]},
  { año:2012, jugadores:[
    {n:'STEKELENBURG', pos:'pt', v:82},{n:'KRUL',           pos:'pt', v:79},
    {n:'PIETERS',      pos:'def',sp:'lb',v:80},{n:'VLAAR',         pos:'def',sp:'cb',v:82},
    {n:'HEITINGA',     pos:'def',sp:'cb',v:82},{n:'VAN BRONCKHORST',pos:'def',sp:'lb',v:77},
    {n:'SNEIJDER',     pos:'med',v:89},{n:'DE JONG',        pos:'med',v:82},{n:'STROOTMAN',pos:'med',v:82},
    {n:'ROBBEN',       pos:'del',sp:'ext',v:91},{n:'VAN PERSIE',  pos:'del',sp:'dc', v:91},
    {n:'HUNTELAAR',    pos:'del',sp:'dc', v:85},{n:'KUYT',         pos:'del',sp:'ext',v:82},
    {n:'VAN DER VAART',pos:'med',v:84},{n:'AFELLAY',        pos:'del',sp:'ext',v:80},
  ]},
  { año:2021, jugadores:[
    {n:'STEKELENBURG', pos:'pt', v:77},{n:'BIJLOW',         pos:'pt', v:81},
    {n:'DUMFRIES',     pos:'def',sp:'lb',v:84},{n:'DE LIGT',       pos:'def',sp:'cb',v:87},
    {n:'DE VRIJ',      pos:'def',sp:'cb',v:87},{n:'BLIND',         pos:'def',sp:'lb',v:82},
    {n:'DE JONG F.',   pos:'med',v:89},{n:'WIJNALDUM',      pos:'med',v:88},{n:'DE ROON',  pos:'med',v:82},
    {n:'DEPAY',        pos:'del',sp:'dc', v:88},{n:'WEGHORST',     pos:'del',sp:'dc', v:83},
    {n:'BERGHUIS',     pos:'del',sp:'ext',v:83},{n:'MALEN',        pos:'del',sp:'ext',v:82},
    {n:'PROMES',       pos:'del',sp:'ext',v:81},{n:'KLAASSEN',     pos:'med',v:81},
  ]},
  { año:2024, jugadores:[
    {n:'FLEKKEN',      pos:'pt', v:80},{n:'BIJLOW',         pos:'pt', v:78},
    {n:'DUMFRIES',     pos:'def',sp:'lb',v:82},{n:'DE LIGT',       pos:'def',sp:'cb',v:86},
    {n:'VAN DIJK',     pos:'def',sp:'cb',v:90},{n:'BLIND',         pos:'def',sp:'lb',v:78},
    {n:'DE JONG F.',   pos:'med',v:89},{n:'SIMONS',         pos:'med',v:83},{n:'SCHOUTEN', pos:'med',v:78},
    {n:'GAKPO',        pos:'del',sp:'ext',v:86},{n:'DEPAY',        pos:'del',sp:'dc', v:86},
    {n:'VEERMAN',      pos:'med',v:80},{n:'MAATSEN',        pos:'def',sp:'lb',v:79},
  ]},
]},

/* ── INGLATERRA ── */
{ id:'england', nombre:'Inglaterra', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', ediciones:[
  { año:1968, jugadores:[
    {n:'Banks',        pos:'pt', v:93},{n:'Stepney',       pos:'pt', v:78},
    {n:'Cohen',        pos:'def',sp:'lb',v:80},{n:'Moore',         pos:'def',sp:'cb',v:93},
    {n:'Charlton J.',  pos:'def',sp:'cb',v:82},{n:'Wilson R.',     pos:'def',sp:'lb',v:79},
    {n:'Stiles',       pos:'med',v:80},{n:'Charlton B.',   pos:'med',v:92},{n:'Ball',    pos:'med',v:85},
    {n:'Hurst',        pos:'del',sp:'dc', v:87},{n:'Peters',       pos:'del',sp:'ext',v:84},
    {n:'Greaves',      pos:'del',sp:'dc', v:90},{n:'Osgood',       pos:'del',sp:'dc', v:79},
  ]},
  { año:1996, jugadores:[
    {n:'Seaman',       pos:'pt', v:87},{n:'Walker I.',     pos:'pt', v:78},
    {n:'Adams',        pos:'def',sp:'cb',v:86},{n:'Pearce',        pos:'def',sp:'lb',v:83},
    {n:'Neville G.',   pos:'def',sp:'lb',v:80},{n:'Campbell',      pos:'def',sp:'cb',v:84},
    {n:'Ince',         pos:'med',v:83},{n:'Gascoigne',     pos:'med',v:89},{n:'McManaman',pos:'med',v:83},
    {n:'Shearer',      pos:'del',sp:'dc', v:92},{n:'Sheringham',   pos:'del',sp:'dc', v:85},
    {n:'Anderton',     pos:'del',sp:'ext',v:79},{n:'Platt',        pos:'med',v:81},
  ]},
  { año:2004, jugadores:[
    {n:'James D.',     pos:'pt', v:82},{n:'Robinson P.',   pos:'pt', v:79},
    {n:'Neville G.',   pos:'def',sp:'lb',v:79},{n:'Terry',         pos:'def',sp:'cb',v:87},
    {n:'Campbell',     pos:'def',sp:'cb',v:86},{n:'Ashley Cole',   pos:'def',sp:'lb',v:84},
    {n:'Lampard',      pos:'med',v:88},{n:'Gerrard',       pos:'med',v:89},{n:'Beckham', pos:'med',v:86},
    {n:'Owen',         pos:'del',sp:'dc', v:85},{n:'Rooney',       pos:'del',sp:'dc', v:87},
    {n:'Scholes',      pos:'med',v:88},{n:'Heskey',        pos:'del',sp:'dc', v:78},
  ]},
  { año:2021, jugadores:[
    {n:'Pickford',     pos:'pt', v:84},{n:'Henderson J.',  pos:'pt', v:76},
    {n:'Walker K.',    pos:'def',sp:'lb',v:83},{n:'Stones',        pos:'def',sp:'cb',v:85},
    {n:'Maguire',      pos:'def',sp:'cb',v:82},{n:'Trippier',      pos:'def',sp:'lb',v:82},
    {n:'Bellingham',   pos:'med',v:88},{n:'Henderson J.',  pos:'med',v:82},{n:'Phillips',pos:'med',v:81},
    {n:'STERLING',     pos:'del',sp:'ext',v:85},{n:'KANE',          pos:'del',sp:'dc', v:90},
    {n:'SAKA',         pos:'del',sp:'ext',v:85},{n:'GREALISH',     pos:'del',sp:'ext',v:84},
  ]},
  { año:2012, jugadores:[
    {n:'HART',         pos:'pt', v:86},{n:'GREEN',          pos:'pt', v:77},
    {n:'COLE A.',      pos:'def',sp:'lb',v:84},{n:'JOHNSON G.',    pos:'def',sp:'lb',v:82},
    {n:'TERRY',        pos:'def',sp:'cb',v:86},{n:'LESCOTT',       pos:'def',sp:'cb',v:82},
    {n:'GERRARD',      pos:'med',v:87},{n:'LAMPARD',        pos:'med',v:87},{n:'PARKER',   pos:'med',v:82},
    {n:'ROONEY',       pos:'del',sp:'dc', v:89},{n:'WELBECK',      pos:'del',sp:'dc', v:82},
    {n:'WALCOTT',      pos:'del',sp:'ext',v:83},{n:'YOUNG A.',     pos:'del',sp:'ext',v:81},
    {n:'HENDERSON',    pos:'med',v:81},{n:'MILNER',         pos:'med',v:82},
  ]},
  { año:2016, jugadores:[
    {n:'HART',         pos:'pt', v:85},{n:'BUTLAND',        pos:'pt', v:80},
    {n:'WALKER',       pos:'def',sp:'lb',v:83},{n:'CAHILL',        pos:'def',sp:'cb',v:84},
    {n:'SMALLING',     pos:'def',sp:'cb',v:83},{n:'ROSE',          pos:'def',sp:'lb',v:82},
    {n:'ROONEY',       pos:'med',v:86},{n:'ALLI',           pos:'med',v:85},{n:'HENDERSON',pos:'med',v:83},
    {n:'VARDY',        pos:'del',sp:'dc', v:85},{n:'KANE',         pos:'del',sp:'dc', v:85},
    {n:'STERLING',     pos:'del',sp:'ext',v:84},{n:'RASHFORD',     pos:'del',sp:'ext',v:82},
    {n:'DIER',         pos:'med',v:82},{n:'WILSHERE',       pos:'med',v:81},
  ]},
  { año:2024, jugadores:[
    {n:'PICKFORD',     pos:'pt', v:85},{n:'HENDERSON D.',   pos:'pt', v:79},
    {n:'WALKER',       pos:'def',sp:'lb',v:83},{n:'TRIPPIER',      pos:'def',sp:'lb',v:83},
    {n:'STONES',       pos:'def',sp:'cb',v:85},{n:'GUEHI',         pos:'def',sp:'cb',v:83},
    {n:'RICE',         pos:'med',v:88},{n:'BELLINGHAM',     pos:'med',v:90},{n:'A-ARNOLD',  pos:'med',v:87},
    {n:'SAKA',         pos:'del',sp:'ext',v:88},{n:'FODEN',        pos:'del',sp:'ext',v:88},
    {n:'KANE',         pos:'del',sp:'dc', v:90},{n:'WATKINS',      pos:'del',sp:'dc', v:84},
    {n:'PALMER',       pos:'med',v:86},{n:'MAINOO',         pos:'med',v:82},
  ]},
]},

/* ── PORTUGAL ── */
{ id:'portugal', nombre:'Portugal', flag:'🇵🇹', ediciones:[
  { año:1984, jugadores:[
    {n:'Bento',        pos:'pt', v:82},{n:'Vítor Damas',   pos:'pt', v:76},
    {n:'Álvaro',       pos:'def',sp:'lb',v:76},{n:'Eurico',        pos:'def',sp:'cb',v:78},
    {n:'Inácio',       pos:'def',sp:'cb',v:80},{n:'Dito',          pos:'def',sp:'lb',v:74},
    {n:'Sousa J.',     pos:'med',v:80},{n:'Chalana',       pos:'med',v:85},{n:'Diamantino',pos:'del',sp:'ext',v:81},
    {n:'Nené',         pos:'med',v:82},{n:'Rui Jordão',    pos:'del',sp:'dc', v:82},
    {n:'Gomes',        pos:'del',sp:'dc', v:77},{n:'Pacheco',      pos:'del',sp:'ext',v:75},
  ]},
  { año:2004, jugadores:[
    {n:'Ricardo P.',   pos:'pt', v:83},{n:'Quim',          pos:'pt', v:76},
    {n:'Miguel',       pos:'def',sp:'lb',v:78},{n:'Fernando Couto',pos:'def',sp:'cb',v:83},
    {n:'Carvalho R.',  pos:'def',sp:'cb',v:85},{n:'Nuno Valente',  pos:'def',sp:'lb',v:79},
    {n:'Costinha',     pos:'med',v:79},{n:'Deco',          pos:'med',v:89},{n:'Maniche',  pos:'med',v:83},
    {n:'Figo',         pos:'del',sp:'ext',v:91},{n:'Ronaldo',      pos:'del',sp:'ext',v:89},
    {n:'Pauleta',      pos:'del',sp:'dc', v:84},{n:'Simão',        pos:'del',sp:'ext',v:81},
  ]},
  { año:2008, jugadores:[
    {n:'RICARDO P.',   pos:'pt', v:82},{n:'QUIM',           pos:'pt', v:77},
    {n:'BOSINGWA',     pos:'def',sp:'lb',v:81},{n:'FERREIRA P.',   pos:'def',sp:'lb',v:80},
    {n:'CARVALHO R.',  pos:'def',sp:'cb',v:87},{n:'PEPE',          pos:'def',sp:'cb',v:86},
    {n:'DECO',         pos:'med',v:87},{n:'TIAGO',          pos:'med',v:83},{n:'MOUTINHO',pos:'med',v:83},
    {n:'SIMÃO',        pos:'del',sp:'ext',v:84},{n:'RONALDO',      pos:'del',sp:'ext',v:95},
    {n:'NANI',         pos:'del',sp:'ext',v:83},{n:'HUGO ALMEIDA', pos:'del',sp:'dc', v:82},
    {n:'POSTIGA',      pos:'del',sp:'dc', v:79},{n:'PETIT',        pos:'med',v:79},
  ]},
  { año:2012, jugadores:[
    {n:'RUI PATRÍCIO', pos:'pt', v:84},{n:'EDUARDO',        pos:'pt', v:78},
    {n:'COENTRAO',     pos:'def',sp:'lb',v:84},{n:'JOAO PEREIRA',  pos:'def',sp:'lb',v:79},
    {n:'PEPE',         pos:'def',sp:'cb',v:87},{n:'BRUNO ALVES',   pos:'def',sp:'cb',v:82},
    {n:'MOUTINHO',     pos:'med',v:85},{n:'VELOSO',         pos:'med',v:80},{n:'RONALDO',  pos:'del',sp:'ext',v:96},
    {n:'NANI',         pos:'del',sp:'ext',v:85},{n:'HUGO ALMEIDA', pos:'del',sp:'dc', v:82},
    {n:'POSTIGA',      pos:'del',sp:'dc', v:79},{n:'VARELA',       pos:'del',sp:'ext',v:79},
    {n:'CUSTODIO',     pos:'med',v:78},{n:'WILLIAM',        pos:'med',v:79},
  ]},
  { año:2021, jugadores:[
    {n:'RUI PATRÍCIO', pos:'pt', v:86},{n:'ANTHONY LOPES',  pos:'pt', v:83},
    {n:'SEMEDO',       pos:'def',sp:'lb',v:83},{n:'GUERREIRO',     pos:'def',sp:'lb',v:85},
    {n:'PEPE',         pos:'def',sp:'cb',v:83},{n:'DIAS',          pos:'def',sp:'cb',v:88},
    {n:'B. FERNANDES', pos:'med',v:90},{n:'SANCHES R.',     pos:'med',v:83},{n:'PALHINHA',pos:'med',v:83},
    {n:'RONALDO',      pos:'del',sp:'dc', v:93},{n:'JOTA D.',      pos:'del',sp:'ext',v:86},
    {n:'JOAO FELIX',   pos:'del',sp:'ext',v:87},{n:'ANDRE SILVA',  pos:'del',sp:'dc', v:83},
    {n:'JOAO CANCELO', pos:'def',sp:'lb',v:86},{n:'CARVALHO R2.',  pos:'med',v:82},
  ]},
  { año:2016, jugadores:[
    {n:'RUI PATRÍCIO', pos:'pt', v:85},{n:'BETO',           pos:'pt', v:75},
    {n:'Vieirinha',    pos:'def',sp:'lb',v:79},{n:'Fonte',         pos:'def',sp:'cb',v:82},
    {n:'Pepe',         pos:'def',sp:'cb',v:85},{n:'Guerreiro',     pos:'def',sp:'lb',v:81},
    {n:'W. Carvalho',  pos:'med',v:82},{n:'Moutinho',      pos:'med',v:84},{n:'R. Sanches',pos:'med',v:82},
    {n:'Quaresma',     pos:'del',sp:'ext',v:82},{n:'Ronaldo',      pos:'del',sp:'dc', v:96},
    {n:'Nani',         pos:'del',sp:'ext',v:82},{n:'Éder',         pos:'del',sp:'dc', v:77},
  ]},
  { año:2024, jugadores:[
    {n:'Costa D.',     pos:'pt', v:84},{n:'Rui Patrício',  pos:'pt', v:79},
    {n:'Dalot',        pos:'def',sp:'lb',v:81},{n:'Rúben Dias',    pos:'def',sp:'cb',v:90},
    {n:'Nuno Mendes',  pos:'def',sp:'lb',v:83},{n:'Cancelo',       pos:'def',sp:'lb',v:84},
    {n:'Vitinha',      pos:'med',v:85},{n:'Bruno Fernandes',pos:'med',v:88},{n:'Palhinha',pos:'med',v:83},
    {n:'Ronaldo',      pos:'del',sp:'dc', v:89},{n:'Leão',         pos:'del',sp:'ext',v:88},
    {n:'Félix',        pos:'del',sp:'ext',v:84},{n:'G. Ramos',     pos:'del',sp:'dc', v:84},
  ]},
]},

/* ── UNIÓN SOVIÉTICA ── */
{ id:'ussr', nombre:'Unión Soviética', flag:'🇷🇺', ediciones:[
  { año:1960, jugadores:[
    {n:'Yashin',       pos:'pt', v:99},{n:'Belyaev',       pos:'pt', v:78},
    {n:'Voinov',       pos:'def',sp:'cb',v:79},{n:'Maslenkin',     pos:'def',sp:'cb',v:78},
    {n:'Krutikov',     pos:'def',sp:'lb',v:75},{n:'Tsarev',        pos:'def',sp:'lb',v:74},
    {n:'Netto',        pos:'med',v:84},{n:'Voronin',       pos:'med',v:82},{n:'Meshki',  pos:'med',v:77},
    {n:'Ivanov',       pos:'del',sp:'ext',v:82},{n:'Ponedelnik',   pos:'del',sp:'dc', v:80},
    {n:'Bubukin',      pos:'del',sp:'dc', v:78},{n:'Metreveli',    pos:'del',sp:'ext',v:80},
  ]},
  { año:1988, jugadores:[
    {n:'Dasayev',      pos:'pt', v:87},{n:'Cherchesov',    pos:'pt', v:78},
    {n:'Demianenko',   pos:'def',sp:'lb',v:80},{n:'Rats',          pos:'def',sp:'lb',v:79},
    {n:'Khidiatulin',  pos:'def',sp:'cb',v:79},{n:'Baltacha',      pos:'def',sp:'cb',v:77},
    {n:'Litovchenko',  pos:'med',v:82},{n:'Mikhailichenko', pos:'med',v:84},{n:'Zavarov', pos:'med',v:83},
    {n:'Belanov',      pos:'del',sp:'ext',v:87},{n:'Protasov',     pos:'del',sp:'dc', v:84},
    {n:'Borodyuk',     pos:'del',sp:'dc', v:78},{n:'Dobrovolsky',  pos:'med',v:81},
  ]},
]},

/* ── CHECOSLOVAQUIA / REP. CHECA ── */
{ id:'czech', nombre:'Checoslovaquia', flag:'🇨🇿', ediciones:[
  { año:1960, jugadores:[
    {n:'Schrojf',      pos:'pt', v:84},{n:'Dolejsi',       pos:'pt', v:73},
    {n:'Lala',         pos:'def',sp:'lb',v:76},{n:'Pluskal',       pos:'def',sp:'cb',v:78},
    {n:'Popluhar',     pos:'def',sp:'cb',v:79},{n:'Novak',         pos:'def',sp:'lb',v:74},
    {n:'Masopust',     pos:'med',v:88},{n:'Bubník',        pos:'med',v:80},{n:'Kvasnak',pos:'med',v:77},
    {n:'Kvašňák',      pos:'del',sp:'dc', v:79},{n:'Kraus',        pos:'del',sp:'dc', v:77},
    {n:'Šťastný',      pos:'del',sp:'ext',v:78},{n:'Jelínek',      pos:'del',sp:'ext',v:76},
  ]},
  { año:1976, jugadores:[
    {n:'Viktor',       pos:'pt', v:87},{n:'Hruška',        pos:'pt', v:74},
    {n:'Dobiaš',       pos:'def',sp:'cb',v:78},{n:'Ončrus',        pos:'def',sp:'cb',v:80},
    {n:'Pivarník',     pos:'def',sp:'lb',v:78},{n:'Bíčovský',      pos:'def',sp:'lb',v:76},
    {n:'Švehlík',      pos:'med',v:79},{n:'Moder',         pos:'med',v:77},{n:'Panenka', pos:'med',v:86},
    {n:'Masný',        pos:'del',sp:'ext',v:82},{n:'Nèhoda',       pos:'del',sp:'dc', v:84},
    {n:'Petráš',       pos:'del',sp:'ext',v:79},{n:'Čapkovič',     pos:'del',sp:'dc', v:81},
  ]},
  { año:1996, jugadores:[
    {n:'KOUBA',        pos:'pt', v:81},{n:'SRNIČEK',        pos:'pt', v:78},
    {n:'KADLEC',       pos:'def',sp:'cb',v:80},{n:'HORNAK',        pos:'def',sp:'cb',v:78},
    {n:'SUCHOPÁREK',   pos:'def',sp:'lb',v:76},{n:'NOVÁK H.',      pos:'def',sp:'lb',v:74},
    {n:'BEJBL',        pos:'med',v:79},{n:'NEDVĚD',         pos:'med',v:87},{n:'BERGER',  pos:'med',v:83},
    {n:'POBORSKÝ',     pos:'del',sp:'ext',v:82},{n:'ŠMICER',       pos:'del',sp:'ext',v:80},
    {n:'KUKA',         pos:'del',sp:'dc', v:81},{n:'FRÝDEK',       pos:'med',v:76},
  ]},
  { año:2008, jugadores:[
    {n:'ČECH',         pos:'pt', v:90},{n:'BLAŽEK',         pos:'pt', v:77},
    {n:'UJFALUŠI',     pos:'def',sp:'cb',v:82},{n:'ROZEHNAL',      pos:'def',sp:'cb',v:80},
    {n:'GRYGERA',      pos:'def',sp:'lb',v:79},{n:'JANKULOVSKI',   pos:'def',sp:'lb',v:82},
    {n:'GALÁSEK',      pos:'med',v:79},{n:'ROSICKÝ',        pos:'del',sp:'ext',v:85},{n:'PLAŠIL', pos:'med',v:82},
    {n:'BAROŠ',        pos:'del',sp:'dc', v:83},{n:'KOLLER',       pos:'del',sp:'dc', v:80},
    {n:'SIONKO',       pos:'del',sp:'ext',v:78},{n:'POLÁK',        pos:'med',v:79},
    {n:'FENIN',        pos:'del',sp:'dc', v:78},{n:'MATĚJOVSKÝ',   pos:'med',v:77},
  ]},
  { año:2012, jugadores:[
    {n:'ČECH',         pos:'pt', v:91},{n:'VACLÍK',         pos:'pt', v:78},
    {n:'GEBRE SELASSIE',pos:'def',sp:'lb',v:79},{n:'SIVOK',        pos:'def',sp:'cb',v:80},
    {n:'KADLEC M.',    pos:'def',sp:'lb',v:80},{n:'LIMBERSKÝ',     pos:'def',sp:'lb',v:79},
    {n:'ROSICKÝ',      pos:'del',sp:'ext',v:84},{n:'PLAŠIL',       pos:'med',v:81},{n:'JIRÁČEK',pos:'med',v:82},
    {n:'BAROŠ',        pos:'del',sp:'dc', v:81},{n:'NEČID',        pos:'del',sp:'dc', v:80},
    {n:'REZEK',        pos:'del',sp:'ext',v:78},{n:'DARIDA',       pos:'med',v:80},
    {n:'HUBSCHMAN',    pos:'med',v:79},{n:'PILAR',          pos:'del',sp:'ext',v:81},
  ]},
  { año:2016, jugadores:[
    {n:'ČECH',         pos:'pt', v:89},{n:'VACLÍK',         pos:'pt', v:82},
    {n:'KADEŘÁBEK',    pos:'def',sp:'lb',v:81},{n:'SIVOK',         pos:'def',sp:'cb',v:79},
    {n:'SUCHÝ',        pos:'def',sp:'cb',v:80},{n:'LIMBERSKÝ',     pos:'def',sp:'lb',v:79},
    {n:'DARIDA',       pos:'med',v:82},{n:'ROSICKÝ',        pos:'del',sp:'ext',v:83},{n:'DOČKAL', pos:'med',v:82},
    {n:'NEČID',        pos:'del',sp:'dc', v:80},{n:'VYDRA',        pos:'del',sp:'dc', v:80},
    {n:'SOUČEK',       pos:'med',v:80},{n:'PILAR',          pos:'del',sp:'ext',v:80},
    {n:'KADLEC M.',    pos:'def',sp:'lb',v:79},{n:'KRMENCÍK',      pos:'del',sp:'dc', v:79},
  ]},
  { año:2021, jugadores:[
    {n:'VACLÍK',       pos:'pt', v:84},{n:'KOVÁŘ',          pos:'pt', v:78},
    {n:'COUFAL',       pos:'def',sp:'lb',v:83},{n:'BOŘIL',         pos:'def',sp:'lb',v:80},
    {n:'ČELŮSTKA',     pos:'def',sp:'cb',v:80},{n:'KALÁS',         pos:'def',sp:'cb',v:80},
    {n:'SOUČEK',       pos:'med',v:87},{n:'DARIDA',         pos:'med',v:82},{n:'BARÁK',   pos:'med',v:83},
    {n:'SCHICK',       pos:'del',sp:'dc', v:85},{n:'KRMENCÍK',     pos:'del',sp:'dc', v:80},
    {n:'JANKTO',       pos:'del',sp:'ext',v:80},{n:'MASOPUST',     pos:'del',sp:'ext',v:79},
    {n:'VYDRA',        pos:'del',sp:'dc', v:80},{n:'SADÍLEK',      pos:'med',v:78},
  ]},
  { año:2024, jugadores:[
    {n:'STANĚK',       pos:'pt', v:82},{n:'KOVÁŘ',          pos:'pt', v:79},
    {n:'COUFAL',       pos:'def',sp:'lb',v:83},{n:'BOŘIL',         pos:'def',sp:'lb',v:80},
    {n:'BRABEC',       pos:'def',sp:'cb',v:79},{n:'HOLES',         pos:'med',v:83},
    {n:'SOUČEK',       pos:'med',v:87},{n:'BARÁK',          pos:'med',v:82},{n:'PROVOD',  pos:'del',sp:'ext',v:81},
    {n:'SCHICK',       pos:'del',sp:'dc', v:85},{n:'CHYTIL',       pos:'del',sp:'dc', v:81},
    {n:'LINGR',        pos:'del',sp:'ext',v:79},{n:'ČERNÝ',        pos:'del',sp:'ext',v:80},
    {n:'OGBU',         pos:'del',sp:'ext',v:78},{n:'SADÍLEK',      pos:'med',v:78},
  ]},
]},

/* ── DINAMARCA ── */
{ id:'denmark', nombre:'Dinamarca', flag:'🇩🇰', ediciones:[
  { año:1984, jugadores:[
    {n:'Qvist',        pos:'pt', v:78},{n:'Busk',          pos:'pt', v:73},
    {n:'Lerby',        pos:'def',sp:'cb',v:82},{n:'Busk S.',       pos:'def',sp:'cb',v:78},
    {n:'Olsen M.',     pos:'def',sp:'lb',v:80},{n:'Sivebæk',       pos:'def',sp:'lb',v:77},
    {n:'Bertelsen',    pos:'med',v:77},{n:'Arnesen',       pos:'med',v:82},{n:'Elkjær',  pos:'del',sp:'ext',v:87},
    {n:'Laudrup M.',   pos:'del',sp:'ext',v:88},{n:'Nielsen S.E.', pos:'del',sp:'dc', v:79},
    {n:'Hansen J.',    pos:'del',sp:'dc', v:77},{n:'Mølby',        pos:'med',v:83},
  ]},
  { año:1992, jugadores:[
    {n:'Schmeichel',   pos:'pt', v:93},{n:'Krogh',         pos:'pt', v:74},
    {n:'Sivebæk',      pos:'def',sp:'lb',v:77},{n:'Olsen M.',      pos:'def',sp:'cb',v:82},
    {n:'Christofte',   pos:'def',sp:'cb',v:79},{n:'Piechnik',      pos:'def',sp:'lb',v:75},
    {n:'Jensen J.',    pos:'med',v:78},{n:'Povlsen',       pos:'med',v:79},{n:'Vilfort',  pos:'med',v:82},
    {n:'Laudrup B.',   pos:'del',sp:'ext',v:85},{n:'Laudrup M.',   pos:'del',sp:'ext',v:91},
    {n:'Jensen B.',    pos:'del',sp:'dc', v:82},{n:'Elstrup',      pos:'del',sp:'dc', v:76},
  ]},
  { año:2012, jugadores:[
    {n:'SØRENSEN',     pos:'pt', v:81},{n:'ANDERSEN K.',    pos:'pt', v:76},
    {n:'AGGER',        pos:'def',sp:'cb',v:85},{n:'KJÆR',          pos:'def',sp:'cb',v:84},
    {n:'BOILESEN',     pos:'def',sp:'lb',v:78},{n:'JACOBSEN L.',   pos:'def',sp:'lb',v:79},
    {n:'KVIST',        pos:'med',v:80},{n:'ROMMEDAHL',      pos:'del',sp:'ext',v:82},{n:'ERIKSEN',pos:'med',v:87},
    {n:'KROHN-DEHLI',  pos:'med',v:81},{n:'BENDTNER',      pos:'del',sp:'dc', v:82},
    {n:'POULSEN',      pos:'del',sp:'ext',v:80},{n:'CHRISTIAN P.', pos:'def',sp:'cb',v:79},
    {n:'SILBERBAUER',  pos:'med',v:77},{n:'SCHÖNE',         pos:'med',v:79},
  ]},
  { año:2021, jugadores:[
    {n:'SCHMEICHEL K.',pos:'pt', v:83},{n:'RØNNOW',         pos:'pt', v:75},
    {n:'WASS',         pos:'def',sp:'lb',v:78},{n:'KJÆR',          pos:'def',sp:'cb',v:83},
    {n:'CHRISTENSEN A.',pos:'def',sp:'cb',v:84},{n:'MÆHLE',        pos:'def',sp:'lb',v:80},
    {n:'DELANEY',      pos:'med',v:81},{n:'HØJBJERG',       pos:'med',v:84},{n:'ERIKSEN',  pos:'med',v:88},
    {n:'BRAITHWAITE',  pos:'del',sp:'dc', v:79},{n:'DOLBERG',      pos:'del',sp:'dc', v:80},
    {n:'DAMSGAARD',    pos:'del',sp:'ext',v:80},{n:'WIND',         pos:'del',sp:'dc', v:77},
  ]},
  { año:2024, jugadores:[
    {n:'SCHMEICHEL K.',pos:'pt', v:83},{n:'FLEKKEN',        pos:'pt', v:79},
    {n:'ANDERSEN J.',  pos:'def',sp:'cb',v:87},{n:'CHRISTENSEN A.',pos:'def',sp:'cb',v:87},
    {n:'VESTERGAARD',  pos:'def',sp:'cb',v:83},{n:'MÆHLE',         pos:'def',sp:'lb',v:83},
    {n:'HØJBJERG',     pos:'med',v:86},{n:'ERIKSEN',        pos:'med',v:88},{n:'HJULMAND',pos:'med',v:83},
    {n:'BRAITHWAITE',  pos:'del',sp:'dc', v:82},{n:'HØJLUND',      pos:'del',sp:'dc', v:85},
    {n:'WIND',         pos:'del',sp:'dc', v:80},{n:'BAH',          pos:'def',sp:'lb',v:80},
    {n:'DELANEY',      pos:'med',v:80},{n:'OLSEN',          pos:'del',sp:'ext',v:81},
  ]},
]},

/* ── BÉLGICA ── */
{ id:'belgium', nombre:'Bélgica', flag:'🇧🇪', ediciones:[
  { año:1980, jugadores:[
    {n:'Pfaff',        pos:'pt', v:89},{n:'Custers',       pos:'pt', v:74},
    {n:'Millecamps',   pos:'def',sp:'lb',v:76},{n:'Meeuws',        pos:'def',sp:'cb',v:77},
    {n:'Renquin',      pos:'def',sp:'lb',v:75},{n:'Gerets',        pos:'def',sp:'lb',v:79},
    {n:'Van Moer',     pos:'med',v:80},{n:'François VdE',  pos:'med',v:78},{n:'Cools',   pos:'med',v:76},
    {n:'Ceulemans',    pos:'del',sp:'dc', v:86},{n:'Van der Elst L.',pos:'del',sp:'ext',v:83},
    {n:'Vandenbergh',  pos:'del',sp:'dc', v:80},{n:'Voordeckers',  pos:'del',sp:'ext',v:76},
  ]},
  { año:2000, jugadores:[
    {n:'De Wolf',      pos:'pt', v:78},{n:'Peeters G.',    pos:'pt', v:74},
    {n:'Deflandre',    pos:'def',sp:'lb',v:77},{n:'Van Meir',      pos:'def',sp:'cb',v:76},
    {n:'Staelens',     pos:'def',sp:'cb',v:78},{n:'Peeters B.',    pos:'def',sp:'lb',v:75},
    {n:'Goor',         pos:'med',v:79},{n:'Nilis',         pos:'del',sp:'dc', v:84},{n:'Wilmots',pos:'del',sp:'dc',v:82},
    {n:'Mpenza E.',    pos:'del',sp:'ext',v:80},{n:'Van der Elst',  pos:'med',v:77},
    {n:'Strupar',      pos:'del',sp:'dc', v:79},{n:'Peeters T.',   pos:'med',v:75},
  ]},
  { año:2016, jugadores:[
    {n:'COURTOIS',     pos:'pt', v:91},{n:'MIGNOLET',       pos:'pt', v:83},
    {n:'ALDERWEIRELD', pos:'def',sp:'cb',v:87},{n:'VERTONGHEN',    pos:'def',sp:'cb',v:87},
    {n:'CIMAN',        pos:'def',sp:'lb',v:80},{n:'MEUNIER',       pos:'def',sp:'lb',v:80},
    {n:'DE BRUYNE',    pos:'med',v:91},{n:'WITSEL',         pos:'med',v:85},{n:'NAINGGOLAN',pos:'med',v:85},
    {n:'HAZARD E.',    pos:'del',sp:'ext',v:91},{n:'LUKAKU',       pos:'del',sp:'dc', v:89},
    {n:'MERTENS',      pos:'del',sp:'ext',v:87},{n:'CARRASCO',     pos:'del',sp:'ext',v:83},
    {n:'FELLAINI',     pos:'med',v:83},{n:'CHADLI',         pos:'del',sp:'ext',v:83},
  ]},
  { año:2021, jugadores:[
    {n:'COURTOIS',     pos:'pt', v:93},{n:'MIGNOLET',       pos:'pt', v:81},
    {n:'ALDERWEIRELD', pos:'def',sp:'cb',v:86},{n:'VERTONGHEN',    pos:'def',sp:'cb',v:84},
    {n:'CASTAGNE',     pos:'def',sp:'lb',v:83},{n:'MEUNIER',       pos:'def',sp:'lb',v:80},
    {n:'DE BRUYNE',    pos:'med',v:94},{n:'WITSEL',         pos:'med',v:84},{n:'TIELEMANS', pos:'med',v:83},
    {n:'HAZARD E.',    pos:'del',sp:'ext',v:88},{n:'LUKAKU',       pos:'del',sp:'dc', v:90},
    {n:'MERTENS',      pos:'del',sp:'ext',v:84},{n:'CARRASCO',     pos:'del',sp:'ext',v:82},
  ]},
  { año:2024, jugadores:[
    {n:'CASTEELS',     pos:'pt', v:84},{n:'MIGNOLET',       pos:'pt', v:83},
    {n:'CASTAGNE',     pos:'def',sp:'lb',v:83},{n:'FAES',          pos:'def',sp:'cb',v:81},
    {n:'VERTONGHEN',   pos:'def',sp:'cb',v:82},{n:'THEATE',        pos:'def',sp:'cb',v:82},
    {n:'DE BRUYNE',    pos:'med',v:89},{n:'ONANA',          pos:'med',v:83},{n:'TIELEMANS', pos:'med',v:85},
    {n:'DOKU',         pos:'del',sp:'ext',v:86},{n:'LUKAKU',       pos:'del',sp:'dc', v:88},
    {n:'OPENDA',       pos:'del',sp:'dc', v:85},{n:'CARRASCO',     pos:'del',sp:'ext',v:82},
    {n:'DE BRUYNE K.', pos:'med',v:88},{n:'VANAKEN',        pos:'med',v:82},
  ]},
]},

/* ── YUGOSLAVIA ── */
{ id:'yugoslavia', nombre:'Yugoslavia', flag:'🇷🇸', ediciones:[
  { año:1960, jugadores:[
    {n:'Vidić B.',     pos:'pt', v:82},{n:'Beara',         pos:'pt', v:84},
    {n:'Durkovic',     pos:'def',sp:'lb',v:75},{n:'Zeković',       pos:'def',sp:'cb',v:77},
    {n:'Jusufi',       pos:'def',sp:'cb',v:76},{n:'Matus',         pos:'def',sp:'lb',v:74},
    {n:'Perušić',      pos:'med',v:78},{n:'Šekularac',     pos:'med',v:83},{n:'Petaković',pos:'med',v:76},
    {n:'Kostić',       pos:'del',sp:'ext',v:85},{n:'Galić',        pos:'del',sp:'dc', v:82},
    {n:'Jovanović',    pos:'del',sp:'dc', v:79},{n:'Zaneti',       pos:'del',sp:'ext',v:77},
  ]},
  { año:1968, jugadores:[
    {n:'Pantelic',     pos:'pt', v:83},{n:'Ćurković',      pos:'pt', v:80},
    {n:'Fazlagic',     pos:'def',sp:'lb',v:76},{n:'Paunović',      pos:'def',sp:'cb',v:79},
    {n:'Holcer',       pos:'def',sp:'cb',v:77},{n:'Djordjević',    pos:'def',sp:'lb',v:75},
    {n:'Trivić',       pos:'med',v:80},{n:'Acimovic',      pos:'med',v:79},{n:'Petkovic', pos:'med',v:77},
    {n:'Džajić',       pos:'del',sp:'ext',v:88},{n:'Musemić',      pos:'del',sp:'dc', v:81},
    {n:'Ostojić',      pos:'del',sp:'dc', v:78},{n:'Nikolić',      pos:'del',sp:'ext',v:76},
  ]},
  { año:1976, jugadores:[
    {n:'Maric',        pos:'pt', v:80},{n:'Katalinski',    pos:'pt', v:74},
    {n:'Buljan',       pos:'def',sp:'lb',v:78},{n:'Katalinski V.', pos:'def',sp:'cb',v:80},
    {n:'Bogicevic',    pos:'def',sp:'cb',v:79},{n:'Petrović',      pos:'def',sp:'lb',v:76},
    {n:'Oblak',        pos:'med',v:80},{n:'Acimovic',      pos:'med',v:79},{n:'Surjak',  pos:'med',v:81},
    {n:'Džajić',       pos:'del',sp:'ext',v:86},{n:'Popivoda',     pos:'del',sp:'dc', v:79},
    {n:'Katalinski I.',pos:'del',sp:'dc', v:77},{n:'Petrović B.',  pos:'del',sp:'ext',v:77},
  ]},
]},

/* ── HUNGRÍA ── */
{ id:'hungary', nombre:'Hungría', flag:'🇭🇺', ediciones:[
  { año:1964, jugadores:[
    {n:'Szentmihályi', pos:'pt', v:83},{n:'Géczi',         pos:'pt', v:74},
    {n:'Mátrai',       pos:'def',sp:'cb',v:79},{n:'Sarosi',        pos:'def',sp:'lb',v:75},
    {n:'Sipos',        pos:'def',sp:'cb',v:76},{n:'Ihász',         pos:'def',sp:'lb',v:74},
    {n:'Solymosi',     pos:'med',v:78},{n:'Göröcs',        pos:'med',v:82},{n:'Farkas',  pos:'med',v:79},
    {n:'Bene',         pos:'del',sp:'ext',v:85},{n:'Albert',       pos:'del',sp:'dc', v:87},
    {n:'Tichy',        pos:'del',sp:'dc', v:82},{n:'Rákosi',       pos:'del',sp:'ext',v:78},
  ]},
  { año:1972, jugadores:[
    {n:'Géczi',        pos:'pt', v:78},{n:'Faragó',        pos:'pt', v:74},
    {n:'Pásztó',       pos:'def',sp:'lb',v:76},{n:'Balint',        pos:'def',sp:'cb',v:78},
    {n:'Juhász',       pos:'def',sp:'cb',v:77},{n:'Szücs',         pos:'def',sp:'lb',v:74},
    {n:'Szőke',        pos:'med',v:79},{n:'Kocsis',        pos:'med',v:76},{n:'Zámbó',   pos:'med',v:77},
    {n:'Bene',         pos:'del',sp:'ext',v:83},{n:'Albert',       pos:'del',sp:'dc', v:85},
    {n:'Branikovits',  pos:'del',sp:'dc', v:78},{n:'Kű',           pos:'del',sp:'ext',v:76},
  ]},
  { año:2016, jugadores:[
    {n:'KIRÁLY',       pos:'pt', v:82},{n:'GULÁCSI',        pos:'pt', v:83},
    {n:'LANG',         pos:'def',sp:'cb',v:81},{n:'JUHÁSZ',        pos:'def',sp:'cb',v:80},
    {n:'FIOLA',        pos:'def',sp:'lb',v:79},{n:'KORHUT',        pos:'def',sp:'lb',v:78},
    {n:'KLEINHEISLER', pos:'med',v:82},{n:'GERA',           pos:'med',v:82},{n:'DZSUDZSÁK',pos:'del',sp:'ext',v:84},
    {n:'SZALAI A.',    pos:'del',sp:'dc', v:83},{n:'PRISKIN',      pos:'del',sp:'dc', v:79},
    {n:'STIEBER',      pos:'del',sp:'ext',v:80},{n:'PINTÉR',       pos:'med',v:78},
    {n:'KALMÁR',       pos:'med',v:80},{n:'NIKOLIĆ',        pos:'del',sp:'dc', v:79},
  ]},
  { año:2021, jugadores:[
    {n:'GULÁCSI',      pos:'pt', v:84},{n:'BOGDÁN',         pos:'pt', v:76},
    {n:'FIOLA',        pos:'def',sp:'lb',v:80},{n:'LANG',          pos:'def',sp:'cb',v:82},
    {n:'ORBÁN W.',     pos:'def',sp:'cb',v:83},{n:'NEGO',          pos:'def',sp:'lb',v:79},
    {n:'KLEINHEISLER', pos:'med',v:81},{n:'SZOBOSZLAI',     pos:'med',v:87},{n:'GAZDAG',  pos:'med',v:82},
    {n:'SALLAI',       pos:'del',sp:'ext',v:83},{n:'SZALAI A.',    pos:'del',sp:'dc', v:80},
    {n:'DZSUDZSÁK',    pos:'del',sp:'ext',v:81},{n:'VARGA R.',     pos:'del',sp:'dc', v:82},
    {n:'KALMÁR',       pos:'med',v:79},{n:'FERENCZI',       pos:'del',sp:'ext',v:78},
  ]},
  { año:2024, jugadores:[
    {n:'GULÁCSI',      pos:'pt', v:84},{n:'DIBUSZ',         pos:'pt', v:80},
    {n:'KERKEZ',       pos:'def',sp:'lb',v:82},{n:'ORBÁN W.',      pos:'def',sp:'cb',v:83},
    {n:'LANG',         pos:'def',sp:'cb',v:83},{n:'FIOLA',         pos:'def',sp:'lb',v:79},
    {n:'SZOBOSZLAI',   pos:'med',v:89},{n:'NAGY A.',        pos:'med',v:81},{n:'SCHÄFER',  pos:'med',v:80},
    {n:'SALLAI',       pos:'del',sp:'ext',v:84},{n:'VARGA R.',     pos:'del',sp:'dc', v:83},
    {n:'GAZDAG',       pos:'med',v:82},{n:'CSOBOTH',        pos:'del',sp:'ext',v:79},
    {n:'STYLES',       pos:'med',v:80},{n:'NEGO',           pos:'def',sp:'lb',v:80},
  ]},
]},

/* ── GRECIA ── */
{ id:'greece', nombre:'Grecia', flag:'🇬🇷', ediciones:[
  { año:2004, jugadores:[
    {n:'Nikopolidis',  pos:'pt', v:84},{n:'Chalkias',      pos:'pt', v:76},
    {n:'Seitaridis',   pos:'def',sp:'lb',v:80},{n:'Dellas',        pos:'def',sp:'cb',v:80},
    {n:'Papadopoulos', pos:'def',sp:'cb',v:79},{n:'Kapsis',        pos:'def',sp:'lb',v:78},
    {n:'Basinas',      pos:'med',v:79},{n:'Kafes',         pos:'med',v:77},{n:'Zagorakis',pos:'med',v:81},
    {n:'Giannakopoulos',pos:'del',sp:'ext',v:79},{n:'Charisteas',  pos:'del',sp:'dc', v:80},
    {n:'VRYZAS',       pos:'del',sp:'dc', v:77},{n:'KARAGOUNIS',   pos:'med',v:82},
  ]},
  { año:2008, jugadores:[
    {n:'NIKOPOLIDIS',  pos:'pt', v:81},{n:'TZORVAS',        pos:'pt', v:80},
    {n:'TOROSIDIS',    pos:'def',sp:'lb',v:82},{n:'KYRGIAKOS',     pos:'def',sp:'cb',v:83},
    {n:'DELLAS',       pos:'def',sp:'cb',v:80},{n:'PAPADOPOULOS',  pos:'def',sp:'cb',v:79},
    {n:'KARAGOUNIS',   pos:'med',v:84},{n:'KATSOURANIS',    pos:'med',v:82},{n:'BASINAS',  pos:'med',v:81},
    {n:'CHARISTEAS',   pos:'del',sp:'dc', v:83},{n:'SALPIGIDIS',   pos:'del',sp:'ext',v:80},
    {n:'GEKAS',        pos:'del',sp:'dc', v:83},{n:'SAMARAS',      pos:'del',sp:'dc', v:81},
    {n:'TZIOLIS',      pos:'med',v:80},{n:'LIBEROPOULOS',   pos:'del',sp:'dc', v:80},
  ]},
  { año:2012, jugadores:[
    {n:'KARNEZIS',     pos:'pt', v:78},{n:'TZORVAS',        pos:'pt', v:80},
    {n:'TOROSIDIS',    pos:'def',sp:'lb',v:82},{n:'HOLEBAS',       pos:'def',sp:'lb',v:80},
    {n:'PAPASTATHOPOULOS',pos:'def',sp:'cb',v:82},{n:'MANOLAS',    pos:'def',sp:'cb',v:79},
    {n:'KARAGOUNIS',   pos:'med',v:83},{n:'KATSOURANIS',    pos:'med',v:81},{n:'TZIOLIS',  pos:'med',v:79},
    {n:'MITROGLOU',    pos:'del',sp:'dc', v:81},{n:'GEKAS',        pos:'del',sp:'dc', v:82},
    {n:'SAMARAS',      pos:'del',sp:'dc', v:82},{n:'SALPIGIDIS',   pos:'del',sp:'ext',v:79},
    {n:'NINIS',        pos:'del',sp:'ext',v:78},{n:'FETFATZIDIS',  pos:'del',sp:'ext',v:79},
  ]},
]},

/* ── CROACIA ── */
{ id:'croatia', nombre:'Croacia', flag:'🇭🇷', ediciones:[
  { año:1996, jugadores:[
    {n:'Ladić',        pos:'pt', v:83},{n:'Butina',        pos:'pt', v:74},
    {n:'Bilić',        pos:'def',sp:'cb',v:82},{n:'Šimić',         pos:'def',sp:'cb',v:80},
    {n:'Jarni',        pos:'def',sp:'lb',v:81},{n:'Štimac',        pos:'def',sp:'lb',v:79},
    {n:'Jurčić',       pos:'med',v:78},{n:'Boban',         pos:'med',v:88},{n:'Prosinečki',pos:'med',v:86},
    {n:'Asanović',     pos:'med',v:82},{n:'Šuker',         pos:'del',sp:'dc', v:88},
    {n:'Vlaović',      pos:'del',sp:'dc', v:79},{n:'Jurić',        pos:'del',sp:'ext',v:77},
  ]},
  { año:2008, jugadores:[
    {n:'PLETIKOSA',    pos:'pt', v:82},{n:'RUNJE',          pos:'pt', v:76},
    {n:'ŠIMUNIĆ',      pos:'def',sp:'cb',v:83},{n:'ĆORLUKA',       pos:'def',sp:'cb',v:82},
    {n:'SRNA',         pos:'def',sp:'lb',v:86},{n:'PRANJIĆ',       pos:'def',sp:'lb',v:80},
    {n:'RAKITIĆ',      pos:'med',v:82},{n:'MODRIĆ',         pos:'med',v:85},{n:'KRANJČAR', pos:'med',v:83},
    {n:'OLIĆ',         pos:'del',sp:'dc', v:84},{n:'EDUARDO',      pos:'del',sp:'dc', v:85},
    {n:'PETRIĆ',       pos:'del',sp:'dc', v:82},{n:'KOVAČ N.',     pos:'med',v:78},
    {n:'LEKO',         pos:'med',v:78},{n:'CLASS',          pos:'del',sp:'ext',v:78},
  ]},
  { año:2012, jugadores:[
    {n:'PLETIKOSA',    pos:'pt', v:81},{n:'RUNJE',          pos:'pt', v:74},
    {n:'ŠIMUNIĆ',      pos:'def',sp:'cb',v:82},{n:'ĆORLUKA',       pos:'def',sp:'cb',v:83},
    {n:'SRNA',         pos:'def',sp:'lb',v:85},{n:'PRANJIĆ',       pos:'def',sp:'lb',v:80},
    {n:'MODRIĆ',       pos:'med',v:89},{n:'RAKITIĆ',        pos:'med',v:85},{n:'KRANJČAR', pos:'med',v:81},
    {n:'MANDŽUKIĆ',    pos:'del',sp:'dc', v:86},{n:'JELAVIĆ',      pos:'del',sp:'dc', v:83},
    {n:'EDUARDO',      pos:'del',sp:'dc', v:83},{n:'KOVAČIĆ',      pos:'med',v:80},
    {n:'OLIĆ',         pos:'del',sp:'dc', v:80},{n:'PETRIĆ',       pos:'del',sp:'dc', v:79},
  ]},
  { año:2016, jugadores:[
    {n:'SUBAŠIĆ',      pos:'pt', v:83},{n:'ĆORLUKA',        pos:'pt', v:74},
    {n:'Srna',         pos:'def',sp:'lb',v:83},{n:'Vida',          pos:'def',sp:'cb',v:81},
    {n:'Lovren',       pos:'def',sp:'cb',v:82},{n:'Strinić',       pos:'def',sp:'lb',v:78},
    {n:'Rakitić',      pos:'med',v:88},{n:'Brozović',      pos:'med',v:84},{n:'Modrić',  pos:'med',v:93},
    {n:'Perišić',      pos:'del',sp:'ext',v:84},{n:'Mandžukić',    pos:'del',sp:'dc', v:84},
    {n:'Rebić',        pos:'del',sp:'ext',v:80},{n:'Kramarić',     pos:'del',sp:'dc', v:82},
  ]},
  { año:2021, jugadores:[
    {n:'LIVAKOVIĆ',    pos:'pt', v:84},{n:'GRBIĆ',          pos:'pt', v:77},
    {n:'VIDA',         pos:'def',sp:'cb',v:82},{n:'LOVREN',        pos:'def',sp:'cb',v:83},
    {n:'JURANOVIĆ',    pos:'def',sp:'lb',v:81},{n:'JEDVAJ',        pos:'def',sp:'lb',v:79},
    {n:'MODRIĆ',       pos:'med',v:90},{n:'BROZOVIĆ',       pos:'med',v:88},{n:'KOVAČIĆ', pos:'med',v:87},
    {n:'KRAMARIĆ',     pos:'del',sp:'dc', v:86},{n:'PERIŠIĆ',      pos:'del',sp:'ext',v:87},
    {n:'REBIĆ',        pos:'del',sp:'ext',v:83},{n:'PAŠALIĆ',      pos:'med',v:83},
    {n:'VLAŠIĆ',       pos:'del',sp:'ext',v:83},{n:'BUDIMIR',      pos:'del',sp:'dc', v:80},
  ]},
  { año:2024, jugadores:[
    {n:'GRBIĆ',        pos:'pt', v:80},{n:'IVUŠIĆ',         pos:'pt', v:75},
    {n:'Juranović',    pos:'def',sp:'lb',v:78},{n:'Gvardiol',      pos:'def',sp:'cb',v:88},
    {n:'Erlić',        pos:'def',sp:'cb',v:80},{n:'Sosa',          pos:'def',sp:'lb',v:78},
    {n:'Kovačić',      pos:'med',v:86},{n:'Brozović',      pos:'med',v:83},{n:'Modrić',  pos:'med',v:89},
    {n:'Perišić',      pos:'del',sp:'ext',v:82},{n:'Kramarić',     pos:'del',sp:'dc', v:83},
    {n:'Pašalić',      pos:'med',v:81},{n:'Budimir',       pos:'del',sp:'dc', v:78},
  ]},
]},

/* ── TURQUÍA ── */
{ id:'turkey', nombre:'Turquía', flag:'🇹🇷', ediciones:[
  { año:2000, jugadores:[
    {n:'Rüştü',        pos:'pt', v:84},{n:'Yıldırım',      pos:'pt', v:74},
    {n:'Alpay',        pos:'def',sp:'cb',v:80},{n:'Bülent K.',     pos:'def',sp:'cb',v:79},
    {n:'Okan',         pos:'def',sp:'lb',v:77},{n:'Ergün',         pos:'def',sp:'lb',v:74},
    {n:'Tugay',        pos:'med',v:83},{n:'Emre B.',       pos:'med',v:82},{n:'Oğuz',    pos:'med',v:78},
    {n:'Nihat K.',     pos:'del',sp:'dc', v:82},{n:'Hakan Şükür',  pos:'del',sp:'dc', v:86},
    {n:'Hasan Şaş',    pos:'del',sp:'ext',v:80},{n:'Arif',         pos:'del',sp:'ext',v:76},
  ]},
  { año:2008, jugadores:[
    {n:'VOLKAN D.',    pos:'pt', v:81},{n:'RECBER',         pos:'pt', v:74},
    {n:'Gökhan G.',    pos:'def',sp:'lb',v:80},{n:'Servet',        pos:'def',sp:'cb',v:79},
    {n:'Hakan B.',     pos:'def',sp:'lb',v:77},{n:'Civril',        pos:'def',sp:'cb',v:74},
    {n:'Hamit A.',     pos:'med',v:82},{n:'Emre B.',       pos:'med',v:80},{n:'Aurelio M.',pos:'med',v:79},
    {n:'KAZIM-RICHARDS',pos:'del',sp:'ext',v:78},{n:'SEMIH',       pos:'del',sp:'dc', v:80},
    {n:'TÜMER',        pos:'del',sp:'dc', v:79},{n:'HALIL A.',     pos:'del',sp:'ext',v:82},
  ]},
  { año:2016, jugadores:[
    {n:'BABACAN',      pos:'pt', v:81},{n:'KIVRAK',         pos:'pt', v:76},
    {n:'GÖNÜL',        pos:'def',sp:'lb',v:81},{n:'TOPAL',         pos:'def',sp:'cb',v:82},
    {n:'BALTA',        pos:'def',sp:'cb',v:80},{n:'ERKIN',         pos:'def',sp:'lb',v:79},
    {n:'İNAN',         pos:'med',v:82},{n:'ÇALHANOĞLU',     pos:'del',sp:'ext',v:84},{n:'TUFAN',   pos:'med',v:81},
    {n:'TOSUN',        pos:'del',sp:'dc', v:81},{n:'MOR',          pos:'del',sp:'ext',v:82},
    {n:'NURI ŞAHİN',   pos:'med',v:83},{n:'BULUT',          pos:'del',sp:'dc', v:80},
    {n:'ŞAHAN',        pos:'med',v:78},{n:'AYHAN',          pos:'def',sp:'cb',v:79},
  ]},
  { año:2024, jugadores:[
    {n:'GÜNOĞLU',      pos:'pt', v:82},{n:'BAYINDIR',       pos:'pt', v:79},
    {n:'MÜLDÜR',       pos:'def',sp:'lb',v:81},{n:'AYHAN',         pos:'def',sp:'cb',v:82},
    {n:'BARDAKÇI',     pos:'def',sp:'cb',v:81},{n:'KADIOGLU',      pos:'def',sp:'lb',v:83},
    {n:'ÇALHANOĞLU',   pos:'med',v:87},{n:'ÖZCAN',          pos:'med',v:82},{n:'YILDIZ',  pos:'del',sp:'ext',v:84},
    {n:'AKTURKOGLU',   pos:'del',sp:'ext',v:83},{n:'GÜLER',        pos:'del',sp:'ext',v:85},
    {n:'TOSUN',        pos:'del',sp:'dc', v:79},{n:'TUFAN',        pos:'med',v:81},
    {n:'DEMIRAL',      pos:'def',sp:'cb',v:83},{n:'KOKCÚ',         pos:'med',v:81},
  ]},
]},

/* ── SUECIA ── */
{ id:'sweden', nombre:'Suecia', flag:'🇸🇪', ediciones:[
  { año:1992, jugadores:[
    {n:'Ravelli',      pos:'pt', v:85},{n:'Hedman',        pos:'pt', v:76},
    {n:'Nilsson R.',   pos:'def',sp:'lb',v:79},{n:'Björklund',     pos:'def',sp:'cb',v:80},
    {n:'Andersson P.', pos:'def',sp:'cb',v:78},{n:'Augustsson',    pos:'def',sp:'lb',v:75},
    {n:'Schwarz',      pos:'med',v:80},{n:'Ingesson',      pos:'med',v:82},{n:'Thern',   pos:'med',v:81},
    {n:'Limpar',       pos:'del',sp:'ext',v:83},{n:'Brolin',       pos:'del',sp:'dc', v:85},
    {n:'Dahlin',       pos:'del',sp:'dc', v:84},{n:'Ekström',      pos:'del',sp:'dc', v:80},
  ]},
  { año:2000, jugadores:[
    {n:'HEDMAN',       pos:'pt', v:80},{n:'ISAKSSON',       pos:'pt', v:74},
    {n:'MELLBERG',     pos:'def',sp:'cb',v:78},{n:'LUCIC',         pos:'def',sp:'cb',v:77},
    {n:'ALEXANDERSSON',pos:'def',sp:'lb',v:79},{n:'EDMAN',         pos:'def',sp:'lb',v:76},
    {n:'LINDEROTH',    pos:'med',v:78},{n:'MJÄLLBY',        pos:'med',v:79},{n:'SVENSSON A.',pos:'med',v:77},
    {n:'LARSSON H.',   pos:'del',sp:'ext',v:89},{n:'ALLBÄCK',      pos:'del',sp:'dc', v:80},
    {n:'WILHELMSSON',  pos:'del',sp:'ext',v:78},{n:'JONSON',       pos:'del',sp:'dc', v:77},
  ]},
  { año:2008, jugadores:[
    {n:'ISAKSSON',     pos:'pt', v:80},{n:'HANSSON',        pos:'pt', v:76},
    {n:'MELLBERG',     pos:'def',sp:'cb',v:80},{n:'LUCIC',         pos:'def',sp:'cb',v:78},
    {n:'ALEXANDERSSON',pos:'def',sp:'lb',v:78},{n:'EDMAN',         pos:'def',sp:'lb',v:78},
    {n:'KÄLLSTRÖM',    pos:'med',v:83},{n:'LINDEROTH',      pos:'med',v:79},{n:'WILHELMSSON',pos:'del',sp:'ext',v:80},
    {n:'LJUNGBERG',    pos:'del',sp:'ext',v:83},{n:'ELMANDER',     pos:'del',sp:'dc', v:82},
    {n:'ROSENBERG',    pos:'del',sp:'dc', v:80},{n:'ALLBÄCK',      pos:'del',sp:'dc', v:78},
    {n:'GRANQVIST',    pos:'def',sp:'cb',v:79},{n:'SVENSSON',      pos:'med',v:78},
  ]},
  { año:2012, jugadores:[
    {n:'ISAKSSON',     pos:'pt', v:80},{n:'LINDEGAARD',     pos:'pt', v:77},
    {n:'GRANQVIST',    pos:'def',sp:'cb',v:82},{n:'MELLBERG',      pos:'def',sp:'cb',v:79},
    {n:'LUSTIG',       pos:'def',sp:'lb',v:81},{n:'OLSSON M.',     pos:'def',sp:'lb',v:80},
    {n:'KÄLLSTRÖM',    pos:'med',v:83},{n:'SVENSSON',       pos:'med',v:78},{n:'IBRAHIMOVIĆ', pos:'del',sp:'dc',v:91},
    {n:'ELMANDER',     pos:'del',sp:'dc', v:81},{n:'TOIVONEN',     pos:'del',sp:'dc', v:81},
    {n:'WILHELMSSON',  pos:'del',sp:'ext',v:79},{n:'WERNBLOOM',    pos:'med',v:79},
    {n:'LARSSON',      pos:'med',v:79},{n:'HAMREN',         pos:'def',sp:'cb',v:77},
  ]},
  { año:2016, jugadores:[
    {n:'OLSEN R.',     pos:'pt', v:81},{n:'ISAKSSON',       pos:'pt', v:77},
    {n:'GRANQVIST',    pos:'def',sp:'cb',v:84},{n:'LINDELÖF',      pos:'def',sp:'cb',v:83},
    {n:'LUSTIG',       pos:'def',sp:'lb',v:82},{n:'OLSSON M.',     pos:'def',sp:'lb',v:80},
    {n:'KÄLLSTRÖM',    pos:'med',v:82},{n:'FORSBERG',       pos:'del',sp:'ext',v:86},{n:'EKDAL',   pos:'med',v:80},
    {n:'IBRAHIMOVIĆ',  pos:'del',sp:'dc', v:92},{n:'BERG',         pos:'del',sp:'dc', v:80},
    {n:'GUIDETTI',     pos:'del',sp:'dc', v:79},{n:'LARSSON',      pos:'del',sp:'ext',v:78},
    {n:'JOHANSSON',    pos:'def',sp:'cb',v:78},{n:'HILJEMARK',     pos:'med',v:79},
  ]},
  { año:2021, jugadores:[
    {n:'OLSEN R.',     pos:'pt', v:82},{n:'JOHNSSON',       pos:'pt', v:80},
    {n:'AUGUSTINSSON', pos:'def',sp:'lb',v:82},{n:'LUSTIG',        pos:'def',sp:'lb',v:81},
    {n:'GRANQVIST',    pos:'def',sp:'cb',v:83},{n:'LINDELÖF',      pos:'def',sp:'cb',v:85},
    {n:'EKDAL',        pos:'med',v:81},{n:'LARSSON',        pos:'del',sp:'ext',v:85},{n:'FORSBERG',pos:'del',sp:'ext',v:87},
    {n:'ISAK',         pos:'del',sp:'dc', v:83},{n:'BERG',         pos:'del',sp:'dc', v:81},
    {n:'QUAISON',      pos:'del',sp:'ext',v:79},{n:'CLAESSON',     pos:'del',sp:'ext',v:79},
    {n:'DANIELSON',    pos:'def',sp:'cb',v:80},{n:'SVANBERG',      pos:'med',v:79},
  ]},
]},

/* ── RUMANÍA ── */
{ id:'romania', nombre:'Rumanía', flag:'🇷🇴', ediciones:[
  { año:1984, jugadores:[
    {n:'Moraru',       pos:'pt', v:79},{n:'Lung',          pos:'pt', v:76},
    {n:'Sames',        pos:'def',sp:'cb',v:76},{n:'Iordănescu',    pos:'def',sp:'cb',v:77},
    {n:'Klein',        pos:'def',sp:'lb',v:74},{n:'Coras',         pos:'def',sp:'lb',v:73},
    {n:'Balaci',       pos:'med',v:80},{n:'Bölöni',        pos:'med',v:82},{n:'Camataru', pos:'del',sp:'dc',v:80},
    {n:'Hagi',         pos:'med',v:88},{n:'Mateuț',        pos:'del',sp:'ext',v:79},
    {n:'Balaci L.',    pos:'del',sp:'dc', v:78},{n:'Rădulescu',    pos:'del',sp:'ext',v:76},
  ]},
  { año:2000, jugadores:[
    {n:'STELEA',       pos:'pt', v:81},{n:'BOGDAN',         pos:'pt', v:74},
    {n:'PETRESCU',     pos:'def',sp:'lb',v:82},{n:'FILIPESCU',     pos:'def',sp:'cb',v:79},
    {n:'CHIVU',        pos:'def',sp:'cb',v:82},{n:'CONTRA',        pos:'def',sp:'lb',v:80},
    {n:'MUNTEANU',     pos:'med',v:82},{n:'POPESCU',        pos:'med',v:83},{n:'MOLDOVAN', pos:'del',sp:'dc',v:81},
    {n:'HAGI',         pos:'med',v:86},{n:'MUTU',           pos:'del',sp:'ext',v:84},
    {n:'GANEA',        pos:'del',sp:'dc', v:79},{n:'ILIE',         pos:'del',sp:'ext',v:80},
  ]},
  { año:2008, jugadores:[
    {n:'LOBONȚ',       pos:'pt', v:79},{n:'LUNG JR.',       pos:'pt', v:75},
    {n:'CONTRA',       pos:'def',sp:'lb',v:80},{n:'RAT',           pos:'def',sp:'lb',v:81},
    {n:'CHIVU',        pos:'def',sp:'cb',v:84},{n:'TAMAȘ',         pos:'def',sp:'cb',v:79},
    {n:'RĂDOI',        pos:'med',v:81},{n:'CODREA',         pos:'med',v:78},{n:'MUTU',    pos:'del',sp:'ext',v:86},
    {n:'MARICA',       pos:'del',sp:'dc', v:82},{n:'DICĂ',         pos:'del',sp:'ext',v:80},
    {n:'GHIOANE',      pos:'med',v:78},{n:'PETRE',          pos:'med',v:77},
    {n:'CERNAT',       pos:'del',sp:'ext',v:78},{n:'NICULAE',      pos:'del',sp:'dc', v:79},
  ]},
  { año:2016, jugadores:[
    {n:'TĂTĂRUȘANU',   pos:'pt', v:82},{n:'LOBONȚ',         pos:'pt', v:76},
    {n:'SĂPUNARU',     pos:'def',sp:'lb',v:78},{n:'RAT',           pos:'def',sp:'lb',v:79},
    {n:'CHIRICHEȘ',    pos:'def',sp:'cb',v:83},{n:'GRIGORE',       pos:'def',sp:'cb',v:79},
    {n:'PINTILII',     pos:'med',v:78},{n:'BUDESCU',        pos:'med',v:81},{n:'STANCU',  pos:'del',sp:'dc', v:81},
    {n:'MAXIM',        pos:'del',sp:'ext',v:79},{n:'ALIBEC',       pos:'del',sp:'dc', v:78},
    {n:'SÂNMARTEAN',   pos:'med',v:79},{n:'ANDONE',         pos:'del',sp:'dc', v:78},
    {n:'HOBAN',        pos:'med',v:78},{n:'POPA',           pos:'med',v:77},
  ]},
  { año:2024, jugadores:[
    {n:'NIȚĂ',         pos:'pt', v:81},{n:'RADU H.',        pos:'pt', v:78},
    {n:'RAȚIU',        pos:'def',sp:'lb',v:81},{n:'BANCU',         pos:'def',sp:'lb',v:79},
    {n:'DRĂGUȘIN',     pos:'def',sp:'cb',v:83},{n:'BURCĂ',         pos:'def',sp:'cb',v:79},
    {n:'MARIN',        pos:'med',v:83},{n:'STANCIU',        pos:'med',v:82},{n:'OLARU',   pos:'med',v:82},
    {n:'HAGI I.',      pos:'del',sp:'ext',v:85},{n:'MAN',          pos:'del',sp:'ext',v:83},
    {n:'ALIBEC',       pos:'del',sp:'dc', v:80},{n:'PUȘCAȘ',       pos:'del',sp:'dc', v:79},
    {n:'MIHAILĂ',      pos:'med',v:79},{n:'RUS',            pos:'def',sp:'cb',v:79},
  ]},
]},

/* ── SUIZA ── */
{ id:'switzerland', nombre:'Suiza', flag:'🇨🇭', ediciones:[
  { año:2008, jugadores:[
    {n:'BENAGLIO',     pos:'pt', v:82},{n:'ZUBERBÜHLER',    pos:'pt', v:76},
    {n:'MAGNIN',       pos:'def',sp:'lb',v:80},{n:'SENDEROS',      pos:'def',sp:'cb',v:82},
    {n:'DJOUROU',      pos:'def',sp:'cb',v:80},{n:'BARNETTA',      pos:'del',sp:'ext',v:81},
    {n:'BEHRAMI',      pos:'med',v:83},{n:'INLER',          pos:'med',v:82},{n:'WICKY',    pos:'med',v:78},
    {n:'FREI A.',      pos:'del',sp:'dc', v:84},{n:'STRELLER',     pos:'del',sp:'dc', v:80},
    {n:'NKUFO',        pos:'del',sp:'dc', v:79},{n:'CABANAS',      pos:'del',sp:'ext',v:78},
    {n:'GRICHTING',    pos:'def',sp:'cb',v:78},{n:'G. FERNANDES',  pos:'med',v:79},
  ]},
  { año:2016, jugadores:[
    {n:'SOMMER',       pos:'pt', v:84},{n:'BÜRKI',          pos:'pt', v:80},
    {n:'LICHTSTEINER', pos:'def',sp:'lb',v:83},{n:'RODRIGUEZ R.',  pos:'def',sp:'lb',v:84},
    {n:'SCHÄR',        pos:'def',sp:'cb',v:83},{n:'DJOUROU',       pos:'def',sp:'cb',v:80},
    {n:'BEHRAMI',      pos:'med',v:82},{n:'INLER',          pos:'med',v:83},{n:'XHAKA',    pos:'med',v:85},
    {n:'SHAQIRI',      pos:'del',sp:'ext',v:86},{n:'SEFEROVIC',    pos:'del',sp:'dc', v:81},
    {n:'EMBOLO',       pos:'del',sp:'dc', v:82},{n:'MEHMEDI',      pos:'del',sp:'ext',v:80},
    {n:'DZEMAILI',     pos:'med',v:80},{n:'DERDIYOK',       pos:'del',sp:'dc', v:79},
  ]},
  { año:2021, jugadores:[
    {n:'SOMMER',       pos:'pt', v:84},{n:'MVOGO',          pos:'pt', v:76},
    {n:'WIDMER',       pos:'def',sp:'lb',v:79},{n:'SCHÄR',         pos:'def',sp:'cb',v:83},
    {n:'AKANJI',       pos:'def',sp:'cb',v:84},{n:'RODRIGUEZ R.',  pos:'def',sp:'lb',v:80},
    {n:'FREULER',      pos:'med',v:82},{n:'XHAKA',          pos:'med',v:84},{n:'ZAKARIA',  pos:'med',v:81},
    {n:'SHAQIRI',      pos:'del',sp:'ext',v:84},{n:'SEFEROVIC',    pos:'del',sp:'dc', v:79},
    {n:'EMBOLO',       pos:'del',sp:'dc', v:81},{n:'VARGAS R.',    pos:'del',sp:'ext',v:80},
  ]},
  { año:2024, jugadores:[
    {n:'SOMMER',       pos:'pt', v:87},{n:'MVOGO',          pos:'pt', v:79},
    {n:'WIDMER',       pos:'def',sp:'lb',v:82},{n:'RODRIGUEZ R.',  pos:'def',sp:'lb',v:83},
    {n:'AKANJI',       pos:'def',sp:'cb',v:85},{n:'ELVEDI',        pos:'def',sp:'cb',v:83},
    {n:'FREULER',      pos:'med',v:84},{n:'XHAKA',          pos:'med',v:87},{n:'SHAQIRI',  pos:'del',sp:'ext',v:84},
    {n:'EMBOLO',       pos:'del',sp:'dc', v:83},{n:'VARGAS R.',    pos:'del',sp:'ext',v:84},
    {n:'ZUBER',        pos:'del',sp:'ext',v:81},{n:'NDOYE',        pos:'del',sp:'ext',v:82},
    {n:'SCHAR',        pos:'def',sp:'cb',v:85},{n:'RIEDER',        pos:'med',v:80},
  ]},
]},

/* ── GALES ── */
{ id:'wales', nombre:'Gales', flag:'🏴󠁧󠁢󠁷󠁬󠁳󠁿', ediciones:[
  { año:2016, jugadores:[
    {n:'Hennessey',    pos:'pt', v:80},{n:'Davies B.',     pos:'pt', v:74},
    {n:'Chester',      pos:'def',sp:'cb',v:78},{n:'Williams A.',   pos:'def',sp:'cb',v:80},
    {n:'Collins',      pos:'def',sp:'cb',v:79},{n:'Taylor N.',     pos:'def',sp:'lb',v:76},
    {n:'Gunter',       pos:'def',sp:'lb',v:75},{n:'Allen',         pos:'med',v:80},
    {n:'Ledley',       pos:'med',v:78},{n:'Ramsey',        pos:'med',v:84},
    {n:'BALE',         pos:'del',sp:'ext',v:89},{n:'ROBSON-KANU',  pos:'del',sp:'dc', v:76},
    {n:'VOKES',        pos:'del',sp:'dc', v:75},
  ]},
  { año:2021, jugadores:[
    {n:'WARD',         pos:'pt', v:80},{n:'HENNESSEY',      pos:'pt', v:78},
    {n:'DAVIES B.',    pos:'def',sp:'lb',v:83},{n:'GUNTER',        pos:'def',sp:'lb',v:79},
    {n:'RODON',        pos:'def',sp:'cb',v:83},{n:'LAWRENCE',      pos:'def',sp:'cb',v:80},
    {n:'ALLEN',        pos:'med',v:82},{n:'AMPADU',         pos:'med',v:82},{n:'BALE',    pos:'del',sp:'ext',v:88},
    {n:'RAMSEY',       pos:'med',v:85},{n:'JAMES D.',       pos:'del',sp:'ext',v:83},
    {n:'WILSON H.',    pos:'del',sp:'dc', v:82},{n:'MOORE K.',     pos:'del',sp:'dc', v:80},
    {n:'NORRINGTON-DAVIES',pos:'def',sp:'lb',v:79},{n:'ROBERTS C.',pos:'del',sp:'ext',v:79},
  ]},
]},

/* ── AUSTRIA ── */
{ id:'austria', nombre:'Austria', flag:'🇦🇹', ediciones:[
  { año:2008, jugadores:[
    {n:'PAYER',        pos:'pt', v:78},{n:'MANDL',          pos:'pt', v:74},
    {n:'STRANZL',      pos:'def',sp:'cb',v:80},{n:'POGATETZ',      pos:'def',sp:'cb',v:79},
    {n:'FUCHS',        pos:'def',sp:'lb',v:81},{n:'GARICS',        pos:'def',sp:'lb',v:78},
    {n:'IVANSCHITZ',   pos:'med',v:80},{n:'AUFHAUSER',      pos:'med',v:78},{n:'SICK',    pos:'med',v:77},
    {n:'VASTIC',       pos:'del',sp:'dc', v:78},{n:'KIENAST',      pos:'del',sp:'dc', v:77},
    {n:'LINZ',         pos:'del',sp:'dc', v:77},{n:'SCHIEMER',     pos:'def',sp:'cb',v:78},
    {n:'STANDFEST',    pos:'def',sp:'lb',v:77},{n:'BAUMGARTLINGER',pos:'med',v:77},
  ]},
  { año:2016, jugadores:[
    {n:'ALMER',        pos:'pt', v:80},{n:'LINDNER',        pos:'pt', v:77},
    {n:'ALABA',        pos:'def',sp:'lb',v:87},{n:'KLEIN',         pos:'def',sp:'lb',v:81},
    {n:'PRÖDL',        pos:'def',sp:'cb',v:82},{n:'HINTEREGGER',   pos:'def',sp:'cb',v:83},
    {n:'BAUMGARTLINGER',pos:'med',v:83},{n:'JUNUZOVIĆ',     pos:'med',v:82},{n:'SABITZER', pos:'del',sp:'ext',v:84},
    {n:'HARNIK',       pos:'del',sp:'ext',v:81},{n:'JANTSCHER',    pos:'del',sp:'ext',v:79},
    {n:'ARNAUTOVIĆ',   pos:'del',sp:'dc', v:83},{n:'DRAGOVIĆ',     pos:'def',sp:'cb',v:82},
    {n:'WIMMER',       pos:'def',sp:'cb',v:79},{n:'OKOTIE',        pos:'del',sp:'dc', v:78},
  ]},
  { año:2021, jugadores:[
    {n:'BACHMANN',     pos:'pt', v:81},{n:'PENTZ',          pos:'pt', v:78},
    {n:'ALABA',        pos:'def',sp:'cb',v:88},{n:'HINTEREGGER',   pos:'def',sp:'cb',v:85},
    {n:'LAINER',       pos:'def',sp:'lb',v:82},{n:'ULMER',         pos:'def',sp:'lb',v:79},
    {n:'LAIMER',       pos:'med',v:83},{n:'GRILLITSCH',     pos:'med',v:82},{n:'SABITZER',pos:'del',sp:'ext',v:85},
    {n:'ARNAUTOVIĆ',   pos:'del',sp:'dc', v:85},{n:'GREGORITSCH',  pos:'del',sp:'dc', v:81},
    {n:'ONISIWO',      pos:'del',sp:'ext',v:79},{n:'KALAJDZIC',    pos:'del',sp:'dc', v:82},
    {n:'SCHLAGER X.',  pos:'med',v:82},{n:'BAUMGARTLINGER', pos:'med',v:81},
  ]},
  { año:2024, jugadores:[
    {n:'PENTZ',        pos:'pt', v:79},{n:'SCHLAGER A.',    pos:'pt', v:74},
    {n:'Trimmel',      pos:'def',sp:'lb',v:77},{n:'Posch',         pos:'def',sp:'lb',v:79},
    {n:'Lienhart',     pos:'def',sp:'cb',v:79},{n:'Trauner',       pos:'def',sp:'cb',v:78},
    {n:'Laimer',       pos:'med',v:83},{n:'Schlager X.',   pos:'med',v:82},{n:'Grillitsch',pos:'med',v:78},
    {n:'Sabitzer',     pos:'del',sp:'ext',v:83},{n:'Arnautovic',   pos:'del',sp:'dc', v:82},
    {n:'Gregoritsch',  pos:'del',sp:'dc', v:79},{n:'Baumgartner',  pos:'del',sp:'ext',v:80},
  ]},
]},

/* ── ESCOCIA ── */
{ id:'scotland', nombre:'Escocia', flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', ediciones:[
  { año:1996, jugadores:[
    {n:'Leighton',     pos:'pt', v:80},{n:'Goram',         pos:'pt', v:82},
    {n:'McKimmie',     pos:'def',sp:'lb',v:76},{n:'McPherson',     pos:'def',sp:'cb',v:78},
    {n:'Calderwood',   pos:'def',sp:'cb',v:77},{n:'Boyd T.',       pos:'def',sp:'lb',v:75},
    {n:'McStay',       pos:'med',v:82},{n:'McCall',        pos:'med',v:79},{n:'Collins J.',pos:'med',v:80},
    {n:'Durie',        pos:'del',sp:'dc', v:78},{n:'McCoist',      pos:'del',sp:'dc', v:83},
    {n:'McAllister',   pos:'med',v:81},{n:'Spencer',       pos:'del',sp:'ext',v:76},
  ]},
  { año:2021, jugadores:[
    {n:'MARSHALL',     pos:'pt', v:82},{n:'McLAUGHLIN',    pos:'pt', v:77},
    {n:"O'DONNELL",    pos:'def',sp:'lb',v:79},{n:'ROBERTSON',     pos:'def',sp:'lb',v:87},
    {n:'HENDRY',       pos:'def',sp:'cb',v:81},{n:'MCTOMINAY',     pos:'med',v:83},
    {n:'ARMSTRONG',    pos:'med',v:81},{n:'McGINN',         pos:'med',v:83},{n:'CHRISTIE',pos:'del',sp:'ext',v:83},
    {n:'ADAMS',        pos:'del',sp:'dc', v:83},{n:'FRASER',       pos:'del',sp:'ext',v:80},
    {n:'FORREST',      pos:'del',sp:'ext',v:80},{n:'NISBET',       pos:'del',sp:'dc', v:79},
    {n:'TAYLOR G.',    pos:'def',sp:'lb',v:79},{n:'TURNBULL',      pos:'med',v:79},
  ]},
  { año:2024, jugadores:[
    {n:'GUNN',         pos:'pt', v:82},{n:'GORDON',         pos:'pt', v:79},
    {n:'ALEXANDER',    pos:'def',sp:'lb',v:82},{n:'ROBERTSON',     pos:'def',sp:'lb',v:87},
    {n:'HENDRY',       pos:'def',sp:'cb',v:82},{n:'MCTOMINAY',     pos:'med',v:84},
    {n:'GILMOUR',      pos:'med',v:83},{n:'McGINN',         pos:'med',v:84},{n:'CHRISTIE',pos:'del',sp:'ext',v:82},
    {n:'ADAMS',        pos:'del',sp:'dc', v:84},{n:'TIERNEY',      pos:'def',sp:'lb',v:83},
    {n:'McGREGOR C.',  pos:'med',v:82},{n:'RALSTON',        pos:'def',sp:'lb',v:80},
    {n:'SHANKLAND',    pos:'del',sp:'dc', v:81},{n:'FERGUSON',     pos:'del',sp:'ext',v:80},
  ]},
]},

/* ── POLONIA ── */
{ id:'poland', nombre:'Polonia', flag:'🇵🇱', ediciones:[
  { año:2008, jugadores:[
    {n:'BORUC',        pos:'pt', v:84},{n:'FABIAŃSKI',      pos:'pt', v:80},
    {n:'WASILEWSKI',   pos:'def',sp:'cb',v:80},{n:'JELEŃ',         pos:'def',sp:'cb',v:78},
    {n:'BOENISCH',     pos:'def',sp:'lb',v:78},{n:'ŻEWŁAKOW',      pos:'def',sp:'lb',v:77},
    {n:'KRZYNÓWEK',    pos:'med',v:81},{n:'GUERREIRO R.',   pos:'med',v:79},{n:'MURAWSKI',pos:'med',v:78},
    {n:'SMOLAREK',     pos:'del',sp:'ext',v:81},{n:'SAGANOWSKI',   pos:'del',sp:'dc', v:79},
    {n:'RASIAK',       pos:'del',sp:'dc', v:79},{n:'BROZ',         pos:'med',v:78},
    {n:'SOBOLEWSKI',   pos:'med',v:77},{n:'LOBODZINSKI',    pos:'med',v:77},
  ]},
  { año:2012, jugadores:[
    {n:'SZCZĘSNY',     pos:'pt', v:85},{n:'BORUC',          pos:'pt', v:83},
    {n:'PISZCZEK',     pos:'def',sp:'lb',v:84},{n:'WAWRZYNIAK',    pos:'def',sp:'lb',v:80},
    {n:'WASILEWSKI',   pos:'def',sp:'cb',v:80},{n:'PERQUIS',       pos:'def',sp:'cb',v:79},
    {n:'BŁASZCZYKOWSKI',pos:'del',sp:'ext',v:84},{n:'OBRANIAK',    pos:'med',v:82},{n:'MURAWSKI',pos:'med',v:79},
    {n:'LEWANDOWSKI',  pos:'del',sp:'dc', v:87},{n:'POLAŃSKI',     pos:'med',v:79},
    {n:'RYBUS',        pos:'def',sp:'lb',v:78},{n:'DUDKA',         pos:'med',v:78},
    {n:'SOBOTA',       pos:'del',sp:'ext',v:78},{n:'TYTON',        pos:'pt', v:78},
  ]},
  { año:2016, jugadores:[
    {n:'SZCZĘSNY',     pos:'pt', v:85},{n:'FABIAŃSKI',      pos:'pt', v:82},
    {n:'PISZCZEK',     pos:'def',sp:'lb',v:84},{n:'GLIK',          pos:'def',sp:'cb',v:85},
    {n:'PAZDAN',       pos:'def',sp:'cb',v:81},{n:'JĘDRZEJCZYK',   pos:'def',sp:'lb',v:81},
    {n:'KRYCHOWIAK',   pos:'med',v:87},{n:'BŁASZCZYKOWSKI', pos:'del',sp:'ext',v:83},{n:'ZIELIŃSKI',pos:'med',v:85},
    {n:'MILIK',        pos:'del',sp:'dc', v:83},{n:'LEWANDOWSKI',  pos:'del',sp:'dc', v:93},
    {n:'GROSICKI',     pos:'del',sp:'ext',v:82},{n:'KAPUSTKA',     pos:'med',v:80},
    {n:'TEODORCZYK',   pos:'del',sp:'dc', v:79},{n:'MILIKOWSKI',   pos:'del',sp:'ext',v:78},
  ]},
  { año:2021, jugadores:[
    {n:'SZCZĘSNY',     pos:'pt', v:88},{n:'FABIAŃSKI',      pos:'pt', v:81},
    {n:'BERESZYŃSKI',  pos:'def',sp:'lb',v:82},{n:'RYBUS',         pos:'def',sp:'lb',v:80},
    {n:'GLIK',         pos:'def',sp:'cb',v:84},{n:'BEDNAREK',      pos:'def',sp:'cb',v:84},
    {n:'KRYCHOWIAK',   pos:'med',v:86},{n:'ZIELIŃSKI',      pos:'med',v:86},{n:'MODER',   pos:'med',v:82},
    {n:'LEWANDOWSKI',  pos:'del',sp:'dc', v:94},{n:'MILIK',        pos:'del',sp:'dc', v:84},
    {n:'GROSICKI',     pos:'del',sp:'ext',v:81},{n:'ŚWIDERSKI',    pos:'del',sp:'dc', v:80},
    {n:'KLICH',        pos:'med',v:81},{n:'HELIK',          pos:'def',sp:'cb',v:79},
  ]},
  { año:2024, jugadores:[
    {n:'SZCZĘSNY',     pos:'pt', v:88},{n:'BUŁKA',          pos:'pt', v:80},
    {n:'CASH',         pos:'def',sp:'lb',v:83},{n:'BEDNAREK',      pos:'def',sp:'cb',v:84},
    {n:'KIWIOR',       pos:'def',sp:'cb',v:82},{n:'FRANKOWSKI',    pos:'def',sp:'lb',v:82},
    {n:'ZIELIŃSKI',    pos:'med',v:86},{n:'KRYCHOWIAK',     pos:'med',v:85},{n:'SZYMAŃSKI',pos:'med',v:83},
    {n:'LEWANDOWSKI',  pos:'del',sp:'dc', v:93},{n:'BUKSA',        pos:'del',sp:'dc', v:80},
    {n:'ŚWIDERSKI',    pos:'del',sp:'dc', v:81},{n:'GROSICKI',     pos:'del',sp:'ext',v:79},
    {n:'KAMIŃSKI',     pos:'med',v:81},{n:'PUCHACZ',        pos:'def',sp:'lb',v:79},
  ]},
]},

/* ── RUSIA ── */
{ id:'russia', nombre:'Rusia', flag:'🇷🇺', ediciones:[
  { año:2008, jugadores:[
    {n:'AKINFEEV',     pos:'pt', v:87},{n:'MALAFEEV',       pos:'pt', v:81},
    {n:'ZHIRKOV',      pos:'def',sp:'lb',v:84},{n:'IGNASHEVICH',   pos:'def',sp:'cb',v:85},
    {n:'BEREZUTSKY V.',pos:'def',sp:'cb',v:81},{n:'ANYUKOV',       pos:'def',sp:'lb',v:82},
    {n:'SEMAK',        pos:'med',v:82},{n:'ZYRYANOV',       pos:'med',v:82},{n:'ARSHAVIN', pos:'del',sp:'ext',v:88},
    {n:'PAVLYUCHENKO', pos:'del',sp:'dc', v:83},{n:'POGREBNYAK',   pos:'del',sp:'dc', v:81},
    {n:'BILYALETDINOV',pos:'del',sp:'ext',v:82},{n:'SEMSHOV',      pos:'med',v:80},
    {n:'SYCHEV',       pos:'del',sp:'dc', v:80},{n:'KOLODIN',      pos:'def',sp:'cb',v:80},
  ]},
  { año:2012, jugadores:[
    {n:'AKINFEEV',     pos:'pt', v:87},{n:'MALAFEEV',       pos:'pt', v:80},
    {n:'ZHIRKOV',      pos:'def',sp:'lb',v:83},{n:'IGNASHEVICH',   pos:'def',sp:'cb',v:84},
    {n:'BEREZUTSKY V.',pos:'def',sp:'cb',v:82},{n:'ANYUKOV',       pos:'def',sp:'lb',v:81},
    {n:'SHIROKOV',     pos:'med',v:83},{n:'DENISOV',        pos:'med',v:82},{n:'ARSHAVIN', pos:'del',sp:'ext',v:86},
    {n:'PAVLYUCHENKO', pos:'del',sp:'dc', v:82},{n:'KERZHAKOV',    pos:'del',sp:'dc', v:82},
    {n:'DZAGOEV',      pos:'med',v:83},{n:'GLUSHAKOV',      pos:'med',v:80},
    {n:'KOKORIN',      pos:'del',sp:'dc', v:80},{n:'BILYALETDINOV',pos:'del',sp:'ext',v:81},
  ]},
  { año:2016, jugadores:[
    {n:'AKINFEEV',     pos:'pt', v:84},{n:'GUILHERME',      pos:'pt', v:79},
    {n:'ZHIRKOV',      pos:'def',sp:'lb',v:81},{n:'IGNASHEVICH',   pos:'def',sp:'cb',v:82},
    {n:'BEREZUTSKY',   pos:'def',sp:'cb',v:80},{n:'KOMBAROV',      pos:'def',sp:'lb',v:80},
    {n:'GLUSHAKOV',    pos:'med',v:81},{n:'DENISOV',        pos:'med',v:81},{n:'CHERYSHEV',pos:'del',sp:'ext',v:82},
    {n:'KOKORIN',      pos:'del',sp:'dc', v:81},{n:'DZAGOEV',      pos:'med',v:82},
    {n:'SHATOV',       pos:'del',sp:'ext',v:80},{n:'SHIROKOV',     pos:'med',v:81},
    {n:'OZDOEV',       pos:'med',v:78},{n:'SMOLNIKOV',      pos:'def',sp:'lb',v:80},
  ]},
  { año:2021, jugadores:[
    {n:'SHUNIN',       pos:'pt', v:80},{n:'SAFONOV',        pos:'pt', v:79},
    {n:'MARIO FERNANDES',pos:'def',sp:'lb',v:82},{n:'DZHIKIYA',   pos:'def',sp:'cb',v:82},
    {n:'SEMENOV',      pos:'def',sp:'cb',v:79},{n:'KARAVAEV',      pos:'def',sp:'lb',v:79},
    {n:'ZOBNIN',       pos:'med',v:83},{n:'GOLOVIN',        pos:'med',v:86},{n:'KUZYAEV', pos:'med',v:82},
    {n:'MIRANCHUK',    pos:'del',sp:'ext',v:83},{n:'CHERYSHEV',    pos:'del',sp:'ext',v:83},
    {n:'DZYUBA',       pos:'del',sp:'dc', v:83},{n:'ZHIRKOV',      pos:'def',sp:'lb',v:78},
    {n:'OZDOEV',       pos:'med',v:80},{n:'IONOV',          pos:'del',sp:'ext',v:78},
  ]},
]},

/* ── UCRANIA ── */
{ id:'ukraine', nombre:'Ucrania', flag:'🇺🇦', ediciones:[
  { año:2012, jugadores:[
    {n:'PYATOV',       pos:'pt', v:84},{n:'KOVAL',          pos:'pt', v:79},
    {n:'KHACHERIDI',   pos:'def',sp:'cb',v:82},{n:'KUCHER',        pos:'def',sp:'cb',v:82},
    {n:'RAKYTSKYI',    pos:'def',sp:'cb',v:84},{n:'SELIN',         pos:'def',sp:'lb',v:79},
    {n:'TYMOSCHUK',    pos:'med',v:84},{n:'YARMOLENKO',     pos:'del',sp:'ext',v:86},{n:'KONOPLYANKA',pos:'del',sp:'ext',v:85},
    {n:'VORONIN',      pos:'del',sp:'dc', v:82},{n:'SHEVCHENKO',   pos:'del',sp:'dc', v:87},
    {n:'MILEVSKIY',    pos:'del',sp:'dc', v:80},{n:'GUSEV',        pos:'del',sp:'ext',v:80},
    {n:'NAZARENKO',    pos:'med',v:79},{n:'ALIEV',          pos:'med',v:80},
  ]},
  { año:2016, jugadores:[
    {n:'PYATOV',       pos:'pt', v:84},{n:'BOYKO',          pos:'pt', v:79},
    {n:'BUTKO',        pos:'def',sp:'lb',v:80},{n:'KHACHERIDI',    pos:'def',sp:'cb',v:82},
    {n:'RAKYTSKYI',    pos:'def',sp:'cb',v:84},{n:'SHAKHOV',       pos:'def',sp:'lb',v:79},
    {n:'SYDORCHUK',    pos:'med',v:81},{n:'STEPANENKO',     pos:'med',v:82},{n:'YARMOLENKO',pos:'del',sp:'ext',v:88},
    {n:'KONOPLYANKA',  pos:'del',sp:'ext',v:86},{n:'SELEZNYOV',    pos:'del',sp:'dc', v:82},
    {n:'ZINCHENKO',    pos:'del',sp:'ext',v:81},{n:'MARLOS',       pos:'del',sp:'ext',v:81},
    {n:'KRAVETS',      pos:'del',sp:'dc', v:80},{n:'ROTAN',        pos:'med',v:80},
  ]},
  { año:2021, jugadores:[
    {n:'BUSHCHAN',     pos:'pt', v:83},{n:'PYATOV',         pos:'pt', v:82},
    {n:'KARAVAEV',     pos:'def',sp:'lb',v:79},{n:'ZABARNYI',      pos:'def',sp:'cb',v:81},
    {n:'MATVIYENKO',   pos:'def',sp:'cb',v:83},{n:'MYKOLENKO',     pos:'def',sp:'lb',v:82},
    {n:'SYDORCHUK',    pos:'med',v:82},{n:'ZINCHENKO',      pos:'del',sp:'ext',v:85},{n:'MALINOVSKYI',pos:'med',v:85},
    {n:'YARMOLENKO',   pos:'del',sp:'ext',v:86},{n:'YAREMCHUK',    pos:'del',sp:'dc', v:84},
    {n:'DOVBYK',       pos:'del',sp:'dc', v:82},{n:'TSYGANKOV',    pos:'del',sp:'ext',v:81},
    {n:'SHAPARENKO',   pos:'med',v:81},{n:'STEPANENKO',     pos:'med',v:82},
  ]},
  { año:2024, jugadores:[
    {n:'TRUBIN',       pos:'pt', v:83},{n:'BUSHCHAN',       pos:'pt', v:82},
    {n:'KARAVAEV',     pos:'def',sp:'lb',v:79},{n:'ZABARNYI',      pos:'def',sp:'cb',v:84},
    {n:'MATVIYENKO',   pos:'def',sp:'cb',v:84},{n:'MYKOLENKO',     pos:'def',sp:'lb',v:84},
    {n:'SUDAKOV',      pos:'med',v:85},{n:'ZINCHENKO',      pos:'med',v:84},{n:'MALINOVSKYI',pos:'med',v:84},
    {n:'YARMOLENKO',   pos:'del',sp:'ext',v:83},{n:'YAREMCHUK',    pos:'del',sp:'dc', v:85},
    {n:'DOVBYK',       pos:'del',sp:'dc', v:85},{n:'TSYGANKOV',    pos:'del',sp:'ext',v:82},
    {n:'SHAPARENKO',   pos:'med',v:83},{n:'MUDRYK',         pos:'del',sp:'ext',v:84},
  ]},
]},

/* ── ESLOVAQUIA ── */
{ id:'slovakia', nombre:'Eslovaquia', flag:'🇸🇰', ediciones:[
  { año:2016, jugadores:[
    {n:'KOZÁČIK',      pos:'pt', v:81},{n:'DÚBRAVKA',       pos:'pt', v:78},
    {n:'PEKARÍK',      pos:'def',sp:'lb',v:80},{n:'ĎURICA',        pos:'def',sp:'cb',v:81},
    {n:'ŠKRTEL',       pos:'def',sp:'cb',v:86},{n:'HUBOČAN',       pos:'def',sp:'lb',v:80},
    {n:'KUCKA',        pos:'med',v:83},{n:'HAMŠÍK',         pos:'med',v:90},{n:'WEISS',    pos:'del',sp:'ext',v:82},
    {n:'DUda',         pos:'del',sp:'ext',v:82},{n:'MÁK',          pos:'del',sp:'ext',v:80},
    {n:'NEMEC',        pos:'del',sp:'dc', v:79},{n:'ŠESTÀK',       pos:'del',sp:'dc', v:80},
    {n:'STOCH',        pos:'del',sp:'ext',v:81},{n:'PEČOVSKÝ',     pos:'med',v:79},
  ]},
  { año:2021, jugadores:[
    {n:'DÚBRAVKA',     pos:'pt', v:83},{n:'RODÁK',          pos:'pt', v:79},
    {n:'PEKARÍK',      pos:'def',sp:'lb',v:80},{n:'GYÖMBÉR',       pos:'def',sp:'cb',v:81},
    {n:'ŠKRTEL',       pos:'def',sp:'cb',v:84},{n:'GREGUŠ',        pos:'def',sp:'lb',v:80},
    {n:'KUCKA',        pos:'med',v:84},{n:'HAMŠÍK',         pos:'med',v:88},{n:'LOBOTKA',  pos:'med',v:85},
    {n:'DUDA',         pos:'del',sp:'ext',v:81},{n:'BOŽENÍK',      pos:'del',sp:'dc', v:80},
    {n:'MÁK',          pos:'del',sp:'ext',v:80},{n:'HARASLÍN',     pos:'del',sp:'ext',v:79},
    {n:'STRELEC',      pos:'del',sp:'dc', v:78},{n:'WEISS',        pos:'del',sp:'ext',v:80},
  ]},
  { año:2024, jugadores:[
    {n:'DÚBRAVKA',     pos:'pt', v:83},{n:'RODÁK',          pos:'pt', v:79},
    {n:'PEKARÍK',      pos:'def',sp:'lb',v:80},{n:'GYÖMBÉR',       pos:'def',sp:'cb',v:81},
    {n:'VAVRO',        pos:'def',sp:'cb',v:81},{n:'HANCKO',        pos:'def',sp:'lb',v:82},
    {n:'LOBOTKA',      pos:'med',v:87},{n:'KUCKA',          pos:'med',v:83},{n:'BÉNES',    pos:'med',v:80},
    {n:'DUDA',         pos:'del',sp:'ext',v:82},{n:'SCHRANZ',      pos:'del',sp:'ext',v:83},
    {n:'BOŽENÍK',      pos:'del',sp:'dc', v:81},{n:'SUSLOV',       pos:'del',sp:'ext',v:80},
    {n:'HARASLÍN',     pos:'del',sp:'ext',v:79},{n:'GREGOR',       pos:'def',sp:'cb',v:79},
  ]},
]},

/* ── ALBANIA ── */
{ id:'albania', nombre:'Albania', flag:'🇦🇱', ediciones:[
  { año:2016, jugadores:[
    {n:'BERISHA E.',   pos:'pt', v:82},{n:'STRAKOSHA',      pos:'pt', v:78},
    {n:'MAVRAJ',       pos:'def',sp:'cb',v:82},{n:'AGOLLI',        pos:'def',sp:'lb',v:83},
    {n:'HYSAJ',        pos:'def',sp:'lb',v:83},{n:'XHAKA G.',      pos:'def',sp:'lb',v:82},
    {n:'CANA',         pos:'med',v:83},{n:'ABRASHI',        pos:'med',v:79},{n:'LENJANI',  pos:'del',sp:'ext',v:79},
    {n:'SADIKU',       pos:'del',sp:'dc', v:82},{n:'BALAJ',        pos:'del',sp:'dc', v:79},
    {n:'GASHI',        pos:'del',sp:'ext',v:79},{n:'ROSHI',        pos:'del',sp:'ext',v:78},
    {n:'MEMUSHAJ',     pos:'med',v:79},{n:'BULKU',          pos:'def',sp:'cb',v:78},
  ]},
  { año:2024, jugadores:[
    {n:'STRAKOSHA',    pos:'pt', v:80},{n:'BERISHA E.',     pos:'pt', v:83},
    {n:'HYSAJ',        pos:'def',sp:'lb',v:82},{n:'DJIMSITI',      pos:'def',sp:'cb',v:83},
    {n:'ISMAJLI',      pos:'def',sp:'cb',v:82},{n:'MITAJ',         pos:'def',sp:'lb',v:79},
    {n:'ASLLANI',      pos:'med',v:82},{n:'RAMADANI',       pos:'med',v:82},{n:'GJASULA',  pos:'med',v:80},
    {n:'BAJRAMI',      pos:'del',sp:'ext',v:83},{n:'BROJA',        pos:'del',sp:'dc', v:83},
    {n:'MANAJ',        pos:'del',sp:'dc', v:81},{n:'LACI',         pos:'med',v:80},
    {n:'SEFERI',       pos:'del',sp:'dc', v:78},{n:'CIKALLESHI',   pos:'del',sp:'dc', v:79},
  ]},
]},

/* ── IRLANDA ── */
{ id:'ireland', nombre:'Irlanda', flag:'🇮🇪', ediciones:[
  { año:2012, jugadores:[
    {n:'GIVEN',        pos:'pt', v:83},{n:'WESTWOOD',       pos:'pt', v:78},
    {n:'O\'SHEA',      pos:'def',sp:'cb',v:82},{n:'McSHANE',       pos:'def',sp:'cb',v:79},
    {n:'WARD S.',      pos:'def',sp:'lb',v:78},{n:'KELLY S.',      pos:'def',sp:'lb',v:79},
    {n:'WHELAN G.',    pos:'med',v:81},{n:'ANDREWS',        pos:'med',v:80},{n:'McGEADY',  pos:'del',sp:'ext',v:82},
    {n:'KEANE R.',     pos:'del',sp:'dc', v:83},{n:'DOYLE K.',     pos:'del',sp:'dc', v:81},
    {n:'COX',          pos:'del',sp:'ext',v:79},{n:'LONG',         pos:'del',sp:'dc', v:80},
    {n:'O\'BRIEN A.',  pos:'def',sp:'cb',v:78},{n:'HUNT',          pos:'del',sp:'ext',v:78},
  ]},
  { año:2016, jugadores:[
    {n:'RANDOLPH',     pos:'pt', v:81},{n:'GIVEN',          pos:'pt', v:79},
    {n:'COLEMAN',      pos:'def',sp:'lb',v:85},{n:'BRADY R.',      pos:'def',sp:'lb',v:83},
    {n:'O\'SHEA',      pos:'def',sp:'cb',v:80},{n:'DUFFY',         pos:'def',sp:'cb',v:82},
    {n:'WHELAN G.',    pos:'med',v:80},{n:'HOOLAHAN',       pos:'med',v:83},{n:'HENDRICK', pos:'med',v:82},
    {n:'LONG',         pos:'del',sp:'dc', v:82},{n:'BRADY R2.',    pos:'del',sp:'ext',v:84},
    {n:'WALTERS',      pos:'del',sp:'dc', v:81},{n:'McGEADY',      pos:'del',sp:'ext',v:80},
    {n:'McCARTHY J.',  pos:'med',v:80},{n:'MURPHY',         pos:'del',sp:'dc', v:78},
  ]},
]},

/* ── ISLANDIA ── */
{ id:'iceland', nombre:'Islandia', flag:'🇮🇸', ediciones:[
  { año:2016, jugadores:[
    {n:'HALLDÓRSSON',  pos:'pt', v:79},{n:'KRISTINSSON',    pos:'pt', v:76},
    {n:'ÁRNASON',      pos:'def',sp:'cb',v:82},{n:'INGASON',       pos:'def',sp:'cb',v:80},
    {n:'SÆVARSSON',    pos:'def',sp:'lb',v:80},{n:'SKÚLASON',      pos:'def',sp:'lb',v:79},
    {n:'GUNNARSSON',   pos:'med',v:82},{n:'SIGURDSSON G.',  pos:'med',v:87},{n:'BJARNASON',pos:'med',v:82},
    {n:'FINNBOGASON',  pos:'del',sp:'dc', v:83},{n:'SIGTHÓRSSON',  pos:'del',sp:'dc', v:82},
    {n:'GUDMUNDSSON',  pos:'del',sp:'ext',v:84},{n:'TRAUSTASON',   pos:'del',sp:'ext',v:79},
    {n:'BÖDVARSSON',   pos:'del',sp:'dc', v:79},{n:'SIGURDSSON B.',pos:'med',v:79},
  ]},
]},

/* ── IRLANDA DEL NORTE ── */
{ id:'northernireland', nombre:'Irlanda del Norte', flag:'🇬🇧', ediciones:[
  { año:2016, jugadores:[
    {n:'McGOVERN',     pos:'pt', v:79},{n:'CARROLL R.',     pos:'pt', v:77},
    {n:'HUGHES A.',    pos:'def',sp:'lb',v:78},{n:'CATHCART',      pos:'def',sp:'cb',v:81},
    {n:'McAULEY',      pos:'def',sp:'cb',v:82},{n:'DALLAS',        pos:'def',sp:'lb',v:81},
    {n:'EVANS J.',     pos:'def',sp:'cb',v:83},{n:'DAVIS S.',      pos:'med',v:83},{n:'NORWOOD',pos:'med',v:80},
    {n:'WARD J.',      pos:'del',sp:'ext',v:80},{n:'LAFFERTY K.',  pos:'del',sp:'dc', v:82},
    {n:'WASHINGTON',   pos:'del',sp:'dc', v:79},{n:'GRIGG',        pos:'del',sp:'dc', v:80},
    {n:'McGINN N.',    pos:'del',sp:'ext',v:79},{n:'BRUNT',        pos:'def',sp:'lb',v:79},
  ]},
]},

/* ── FINLANDIA ── */
{ id:'finland', nombre:'Finlandia', flag:'🇫🇮', ediciones:[
  { año:2021, jugadores:[
    {n:'HRADECKY',     pos:'pt', v:83},{n:'JORONEN',        pos:'pt', v:78},
    {n:'ARAJUURI',     pos:'def',sp:'cb',v:80},{n:'OJALA',         pos:'def',sp:'cb',v:79},
    {n:'TOIVIO',       pos:'def',sp:'cb',v:79},{n:'URONEN',        pos:'def',sp:'lb',v:80},
    {n:'RAITALA',      pos:'def',sp:'lb',v:78},{n:'SPARV',         pos:'med',v:81},{n:'KAMARA G.',pos:'med',v:83},
    {n:'LOD',          pos:'del',sp:'ext',v:80},{n:'PUKKI',        pos:'del',sp:'dc', v:85},
    {n:'POHJANPALO',   pos:'del',sp:'dc', v:82},{n:'JENSEN F.',    pos:'del',sp:'ext',v:80},
    {n:'FORSS',        pos:'del',sp:'dc', v:78},{n:'SCHÜLLER',     pos:'def',sp:'cb',v:78},
  ]},
]},

/* ── MACEDONIA DEL NORTE ── */
{ id:'northmacedonia', nombre:'Macedonia del Norte', flag:'🇲🇰', ediciones:[
  { año:2021, jugadores:[
    {n:'DIMITRIEVSKI',  pos:'pt', v:79},{n:'GACEVSKI',      pos:'pt', v:74},
    {n:'MUSLIU',        pos:'def',sp:'cb',v:79},{n:'RISTOVSKI',    pos:'def',sp:'lb',v:79},
    {n:'ALIOSKI',       pos:'def',sp:'lb',v:81},{n:'BEJTULAI',     pos:'def',sp:'cb',v:77},
    {n:'ADEMI',         pos:'med',v:80},{n:'BARDHI',        pos:'med',v:79},{n:'ELMAS',    pos:'med',v:83},
    {n:'TRICKOVSKI',    pos:'del',sp:'ext',v:80},{n:'NESTOROVSKI', pos:'del',sp:'dc', v:81},
    {n:'PANDEV',        pos:'del',sp:'ext',v:84},{n:'TRAJKOVSKI',  pos:'del',sp:'ext',v:80},
    {n:'HASANI',        pos:'del',sp:'ext',v:79},{n:'CHURLINOV',   pos:'del',sp:'ext',v:79},
  ]},
]},

/* ── ESLOVENIA ── */
{ id:'slovenia', nombre:'Eslovenia', flag:'🇸🇮', ediciones:[
  { año:2024, jugadores:[
    {n:'OBLAK',        pos:'pt', v:91},{n:'VIDMAR',         pos:'pt', v:78},
    {n:'STOJANOVIĆ',   pos:'def',sp:'lb',v:81},{n:'BIJOL',         pos:'def',sp:'cb',v:83},
    {n:'BLAŽIČ',       pos:'def',sp:'cb',v:79},{n:'KARNIČNIK',     pos:'def',sp:'lb',v:80},
    {n:'ELŠNIK',       pos:'med',v:80},{n:'CERIN',          pos:'med',v:81},{n:'LOVRIĆ',   pos:'med',v:83},
    {n:'MLAKAR',       pos:'del',sp:'ext',v:79},{n:'ŠPORAR',       pos:'del',sp:'dc', v:80},
    {n:'ŠEŠKO',        pos:'del',sp:'dc', v:84},{n:'VERBIČ',       pos:'del',sp:'ext',v:80},
    {n:'VIPOTNIK',     pos:'del',sp:'dc', v:78},{n:'JANZA',        pos:'def',sp:'lb',v:79},
  ]},
]},

/* ── SERBIA ── */
{ id:'serbia', nombre:'Serbia', flag:'🇷🇸', ediciones:[
  { año:2024, jugadores:[
    {n:'RAJKOVIĆ',     pos:'pt', v:82},{n:'DMITROVIĆ',      pos:'pt', v:80},
    {n:'MILENKOVIĆ',   pos:'def',sp:'cb',v:84},{n:'PAVLOVIĆ',      pos:'def',sp:'cb',v:81},
    {n:'SPAJIĆ',       pos:'def',sp:'cb',v:81},{n:'ŽIVKOVIĆ A.',   pos:'def',sp:'lb',v:81},
    {n:'LUKIĆ',        pos:'med',v:82},{n:'GUDELJ',         pos:'med',v:80},{n:'SAMARDZIĆ',pos:'med',v:82},
    {n:'TADIĆ',        pos:'del',sp:'ext',v:87},{n:'MITROVIĆ',     pos:'del',sp:'dc', v:87},
    {n:'VLAHOVIĆ',     pos:'del',sp:'dc', v:87},{n:'JOVIĆ L.',     pos:'del',sp:'dc', v:82},
    {n:'LAZOVIĆ',      pos:'def',sp:'lb',v:80},{n:'MAKSIMOVIĆ',    pos:'med',v:81},
  ]},
]},

/* ── GEORGIA ── */
{ id:'georgia', nombre:'Georgia', flag:'🇬🇪', ediciones:[
  { año:2024, jugadores:[
    {n:'MAMARDASHVILI', pos:'pt', v:85},{n:'LORIA',         pos:'pt', v:77},
    {n:'KAKABADZE',    pos:'def',sp:'lb',v:80},{n:'DVALI',         pos:'def',sp:'cb',v:81},
    {n:'KVERKVELIA',   pos:'def',sp:'cb',v:79},{n:'LOCHOSHVILI',   pos:'def',sp:'cb',v:80},
    {n:'KOCHORASHVILI',pos:'med',v:82},{n:'CHAKVETADZE',    pos:'del',sp:'ext',v:83},{n:'GVELESIANI',pos:'def',sp:'lb',v:79},
    {n:'KVILITAIA',    pos:'del',sp:'dc', v:80},{n:'MIKAUTADZE',   pos:'del',sp:'dc', v:85},
    {n:'ZIVZIVADZE',   pos:'del',sp:'dc', v:79},{n:'DAVITASHVILI', pos:'del',sp:'ext',v:81},
    {n:'LOBJANIDZE',   pos:'del',sp:'ext',v:80},{n:'TSITAISHVILI', pos:'del',sp:'ext',v:79},
  ]},
]},

];

/* ══════════════════════════════════════
   RIVALES PARA GENERACIÓN DE PARTIDOS
══════════════════════════════════════ */
const RIVALES_EURO = [
  // Tier 1 — élite
  {nombre:'Alemania',     fuerza:89, flag:'🇩🇪', tier:1},
  {nombre:'Francia',      fuerza:89, flag:'🇫🇷', tier:1},
  {nombre:'España',       fuerza:90, flag:'🇪🇸', tier:1},
  {nombre:'Italia',       fuerza:87, flag:'🇮🇹', tier:1},
  {nombre:'Países Bajos', fuerza:88, flag:'🇳🇱', tier:1},
  {nombre:'Inglaterra',   fuerza:86, flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', tier:1},
  {nombre:'Portugal',     fuerza:87, flag:'🇵🇹', tier:1},
  {nombre:'Bélgica',      fuerza:85, flag:'🇧🇪', tier:1},
  // Tier 2 — sólidas
  {nombre:'Croacia',      fuerza:83, flag:'🇭🇷', tier:2},
  {nombre:'Rep. Checa',   fuerza:81, flag:'🇨🇿', tier:2},
  {nombre:'URSS',         fuerza:83, flag:'🇷🇺', tier:2},
  {nombre:'Dinamarca',    fuerza:82, flag:'🇩🇰', tier:2},
  {nombre:'Yugoslavia',   fuerza:82, flag:'🇷🇸', tier:2},
  {nombre:'Turquía',      fuerza:80, flag:'🇹🇷', tier:2},
  {nombre:'Suecia',       fuerza:80, flag:'🇸🇪', tier:2},
  {nombre:'Rumanía',      fuerza:80, flag:'🇷🇴', tier:2},
  {nombre:'Grecia',       fuerza:79, flag:'🇬🇷', tier:2},
  {nombre:'Hungría',      fuerza:80, flag:'🇭🇺', tier:2},
  // Tier 3 — resto
  {nombre:'Suiza',        fuerza:78, flag:'🇨🇭', tier:3},
  {nombre:'Gales',        fuerza:77, flag:'🏴󠁧󠁢󠁷󠁬󠁳󠁿', tier:3},
  {nombre:'Austria',      fuerza:77, flag:'🇦🇹', tier:3},
  {nombre:'Escocia',      fuerza:76, flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', tier:3},
  {nombre:'Polonia',      fuerza:77, flag:'🇵🇱', tier:3},
  {nombre:'Serbia',       fuerza:76, flag:'🇷🇸', tier:3},
  {nombre:'Ucrania',      fuerza:77, flag:'🇺🇦', tier:3},
  {nombre:'Rep. Irlanda', fuerza:75, flag:'🇮🇪', tier:3},
  {nombre:'Albania',      fuerza:72, flag:'🇦🇱', tier:3},
  {nombre:'Eslovaquia',   fuerza:74, flag:'🇸🇰', tier:3},
  {nombre:'Eslovenia',    fuerza:73, flag:'🇸🇮', tier:3},
  {nombre:'Islandia',     fuerza:74, flag:'🇮🇸', tier:3},
  {nombre:'Bulgaria',          fuerza:75, flag:'🇧🇬', tier:3},
  {nombre:'Finlandia',         fuerza:72, flag:'🇫🇮', tier:3},
  {nombre:'Georgia',           fuerza:74, flag:'🇬🇪', tier:3},
  {nombre:'Macedonia del Norte',fuerza:71, flag:'🇲🇰', tier:3},
  {nombre:'Irlanda del Norte', fuerza:72, flag:'🇬🇧', tier:3},
  {nombre:'Irlanda',           fuerza:75, flag:'🇮🇪', tier:3},
  {nombre:'Rusia',             fuerza:80, flag:'🇷🇺', tier:2},
  {nombre:'Polonia',           fuerza:79, flag:'🇵🇱', tier:2},
  {nombre:'Ucrania',           fuerza:78, flag:'🇺🇦', tier:2},
];
